CREATE TABLE dbo.Locations (
  Id INT IDENTITY(1, 1) NOT NULL,
  ProvinceId INT,
  CountyId INT,
  Title NVARCHAR(250) NOT NULL,
  
  CONSTRAINT PK_Locations PRIMARY KEY (Id)
);

INSERT INTO dbo.Locations VALUES (NULL, NULL, N' آذربایجان شرقی')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' آذربایجان غربی')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' اردبیل')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' اصفهان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' البرز')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' ایلام')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' بوشهر')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' تهران')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' چهارمحال وبختیاری')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' خراسان جنوبی')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' خراسان رضوی')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' خراسان شمالی')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' خوزستان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' زنجان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' سمنان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' سیستان وبلوچستان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' فارس')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' قزوین')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' قم')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' کردستان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' کرمان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' کرمانشاه')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' کهگیلویه وبویراحمد')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' گلستان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' گیلان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' لرستان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' مازندران')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' مرکزی')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' هرمزگان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' همدان')
INSERT INTO dbo.Locations VALUES (NULL, NULL, N' یزد')
INSERT INTO dbo.Locations VALUES (1, NULL, N' آذرشهر')
INSERT INTO dbo.Locations VALUES (1, NULL, N' اسکو')
INSERT INTO dbo.Locations VALUES (1, NULL, N' اهر')
INSERT INTO dbo.Locations VALUES (1, NULL, N' بستان آباد')
INSERT INTO dbo.Locations VALUES (1, NULL, N' بناب')
INSERT INTO dbo.Locations VALUES (1, NULL, N' تبریز')
INSERT INTO dbo.Locations VALUES (1, NULL, N' جلفا')
INSERT INTO dbo.Locations VALUES (1, NULL, N' چاراویماق')
INSERT INTO dbo.Locations VALUES (1, NULL, N' خداآفرین')
INSERT INTO dbo.Locations VALUES (1, NULL, N' سراب')
INSERT INTO dbo.Locations VALUES (1, NULL, N' شبستر')
INSERT INTO dbo.Locations VALUES (1, NULL, N' عجب شیر')
INSERT INTO dbo.Locations VALUES (1, NULL, N' کلیبر')
INSERT INTO dbo.Locations VALUES (1, NULL, N' مراغه')
INSERT INTO dbo.Locations VALUES (1, NULL, N' مرند')
INSERT INTO dbo.Locations VALUES (1, NULL, N' ملکان')
INSERT INTO dbo.Locations VALUES (1, NULL, N' میانه')
INSERT INTO dbo.Locations VALUES (1, NULL, N' ورزقان')
INSERT INTO dbo.Locations VALUES (1, NULL, N' هریس')
INSERT INTO dbo.Locations VALUES (1, NULL, N' هشترود')
INSERT INTO dbo.Locations VALUES (2, NULL, N' ارومیه')
INSERT INTO dbo.Locations VALUES (2, NULL, N' اشنویه')
INSERT INTO dbo.Locations VALUES (2, NULL, N' بوکان')
INSERT INTO dbo.Locations VALUES (2, NULL, N' پلدشت')
INSERT INTO dbo.Locations VALUES (2, NULL, N' پیرانشهر')
INSERT INTO dbo.Locations VALUES (2, NULL, N' تکاب')
INSERT INTO dbo.Locations VALUES (2, NULL, N' چالدران')
INSERT INTO dbo.Locations VALUES (2, NULL, N' چایپاره')
INSERT INTO dbo.Locations VALUES (2, NULL, N' خوی')
INSERT INTO dbo.Locations VALUES (2, NULL, N' سردشت')
INSERT INTO dbo.Locations VALUES (2, NULL, N' سلماس')
INSERT INTO dbo.Locations VALUES (2, NULL, N' شاهین دژ')
INSERT INTO dbo.Locations VALUES (2, NULL, N' شوط')
INSERT INTO dbo.Locations VALUES (2, NULL, N' ماکو')
INSERT INTO dbo.Locations VALUES (2, NULL, N' مهاباد')
INSERT INTO dbo.Locations VALUES (2, NULL, N' میاندوآب')
INSERT INTO dbo.Locations VALUES (2, NULL, N' نقده')
INSERT INTO dbo.Locations VALUES (3, NULL, N' اردبیل')
INSERT INTO dbo.Locations VALUES (3, NULL, N' بیله سوار')
INSERT INTO dbo.Locations VALUES (3, NULL, N' پارس آباد')
INSERT INTO dbo.Locations VALUES (3, NULL, N' خلخال')
INSERT INTO dbo.Locations VALUES (3, NULL, N' سرعین')
INSERT INTO dbo.Locations VALUES (3, NULL, N' کوثر')
INSERT INTO dbo.Locations VALUES (3, NULL, N' گرمی')
INSERT INTO dbo.Locations VALUES (3, NULL, N' مشگین شهر')
INSERT INTO dbo.Locations VALUES (3, NULL, N' نمین')
INSERT INTO dbo.Locations VALUES (3, NULL, N' نیر')
INSERT INTO dbo.Locations VALUES (4, NULL, N' آران وبیدگل')
INSERT INTO dbo.Locations VALUES (4, NULL, N' اردستان')
INSERT INTO dbo.Locations VALUES (4, NULL, N' اصفهان')
INSERT INTO dbo.Locations VALUES (4, NULL, N' برخوار')
INSERT INTO dbo.Locations VALUES (4, NULL, N' بو یین و میاندشت')
INSERT INTO dbo.Locations VALUES (4, NULL, N' تیران وکرون')
INSERT INTO dbo.Locations VALUES (4, NULL, N' چادگان')
INSERT INTO dbo.Locations VALUES (4, NULL, N' خمینی شهر')
INSERT INTO dbo.Locations VALUES (4, NULL, N' خوانسار')
INSERT INTO dbo.Locations VALUES (4, NULL, N' خور و بیابانک')
INSERT INTO dbo.Locations VALUES (4, NULL, N' دهاقان')
INSERT INTO dbo.Locations VALUES (4, NULL, N' سمیرم')
INSERT INTO dbo.Locations VALUES (4, NULL, N' شاهین شهرومیمه')
INSERT INTO dbo.Locations VALUES (4, NULL, N' شهرضا')
INSERT INTO dbo.Locations VALUES (4, NULL, N' فریدن')
INSERT INTO dbo.Locations VALUES (4, NULL, N' فریدونشهر')
INSERT INTO dbo.Locations VALUES (4, NULL, N' فلاورجان')
INSERT INTO dbo.Locations VALUES (4, NULL, N' کاشان')
INSERT INTO dbo.Locations VALUES (4, NULL, N' گلپایگان')
INSERT INTO dbo.Locations VALUES (4, NULL, N' لنجان')
INSERT INTO dbo.Locations VALUES (4, NULL, N' مبارکه')
INSERT INTO dbo.Locations VALUES (4, NULL, N' نایین')
INSERT INTO dbo.Locations VALUES (4, NULL, N' نجف آباد')
INSERT INTO dbo.Locations VALUES (4, NULL, N' نطنز')
INSERT INTO dbo.Locations VALUES (5, NULL, N' اشتهارد')
INSERT INTO dbo.Locations VALUES (5, NULL, N' ساوجبلاغ')
INSERT INTO dbo.Locations VALUES (5, NULL, N' طالقان')
INSERT INTO dbo.Locations VALUES (5, NULL, N' فردیس')
INSERT INTO dbo.Locations VALUES (5, NULL, N' کرج')
INSERT INTO dbo.Locations VALUES (5, NULL, N' نظرآباد')
INSERT INTO dbo.Locations VALUES (6, NULL, N' آبدانان')
INSERT INTO dbo.Locations VALUES (6, NULL, N' ایلام')
INSERT INTO dbo.Locations VALUES (6, NULL, N' ایوان')
INSERT INTO dbo.Locations VALUES (6, NULL, N' بدره')
INSERT INTO dbo.Locations VALUES (6, NULL, N' چرداول')
INSERT INTO dbo.Locations VALUES (6, NULL, N' دره شهر')
INSERT INTO dbo.Locations VALUES (6, NULL, N' دهلران')
INSERT INTO dbo.Locations VALUES (6, NULL, N' سیروان')
INSERT INTO dbo.Locations VALUES (6, NULL, N' ملکشاهی')
INSERT INTO dbo.Locations VALUES (6, NULL, N' مهران')
INSERT INTO dbo.Locations VALUES (7, NULL, N' بوشهر')
INSERT INTO dbo.Locations VALUES (7, NULL, N' تنگستان')
INSERT INTO dbo.Locations VALUES (7, NULL, N' جم')
INSERT INTO dbo.Locations VALUES (7, NULL, N' دشتستان')
INSERT INTO dbo.Locations VALUES (7, NULL, N' دشتی')
INSERT INTO dbo.Locations VALUES (7, NULL, N' دیر')
INSERT INTO dbo.Locations VALUES (7, NULL, N' دیلم')
INSERT INTO dbo.Locations VALUES (7, NULL, N' عسلویه')
INSERT INTO dbo.Locations VALUES (7, NULL, N' کنگان')
INSERT INTO dbo.Locations VALUES (7, NULL, N' گناوه')
INSERT INTO dbo.Locations VALUES (8, NULL, N' اسلامشهر')
INSERT INTO dbo.Locations VALUES (8, NULL, N' بهارستان')
INSERT INTO dbo.Locations VALUES (8, NULL, N' پاکدشت')
INSERT INTO dbo.Locations VALUES (8, NULL, N' پردیس')
INSERT INTO dbo.Locations VALUES (8, NULL, N' پیشوا')
INSERT INTO dbo.Locations VALUES (8, NULL, N' تهران')
INSERT INTO dbo.Locations VALUES (8, NULL, N' دماوند')
INSERT INTO dbo.Locations VALUES (8, NULL, N' رباطکریم')
INSERT INTO dbo.Locations VALUES (8, NULL, N' ری')
INSERT INTO dbo.Locations VALUES (8, NULL, N' شمیرانات')
INSERT INTO dbo.Locations VALUES (8, NULL, N' شهریار')
INSERT INTO dbo.Locations VALUES (8, NULL, N' فیروزکوه')
INSERT INTO dbo.Locations VALUES (8, NULL, N' قدس')
INSERT INTO dbo.Locations VALUES (8, NULL, N' قرچک')
INSERT INTO dbo.Locations VALUES (8, NULL, N' ملارد')
INSERT INTO dbo.Locations VALUES (8, NULL, N' ورامین')
INSERT INTO dbo.Locations VALUES (9, NULL, N' اردل')
INSERT INTO dbo.Locations VALUES (9, NULL, N' بروجن')
INSERT INTO dbo.Locations VALUES (9, NULL, N' بن')
INSERT INTO dbo.Locations VALUES (9, NULL, N' سامان')
INSERT INTO dbo.Locations VALUES (9, NULL, N' شهرکرد')
INSERT INTO dbo.Locations VALUES (9, NULL, N' فارسان')
INSERT INTO dbo.Locations VALUES (9, NULL, N' کوهرنگ')
INSERT INTO dbo.Locations VALUES (9, NULL, N' کیار')
INSERT INTO dbo.Locations VALUES (9, NULL, N' لردگان')
INSERT INTO dbo.Locations VALUES (10, NULL, N' بشرویه')
INSERT INTO dbo.Locations VALUES (10, NULL, N' بیرجند')
INSERT INTO dbo.Locations VALUES (10, NULL, N' خوسف')
INSERT INTO dbo.Locations VALUES (10, NULL, N' درمیان')
INSERT INTO dbo.Locations VALUES (10, NULL, N' زیرکوه')
INSERT INTO dbo.Locations VALUES (10, NULL, N' سرایان')
INSERT INTO dbo.Locations VALUES (10, NULL, N' سربیشه')
INSERT INTO dbo.Locations VALUES (10, NULL, N' طبس')
INSERT INTO dbo.Locations VALUES (10, NULL, N' فردوس')
INSERT INTO dbo.Locations VALUES (10, NULL, N' قاینات')
INSERT INTO dbo.Locations VALUES (10, NULL, N' نهبندان')
INSERT INTO dbo.Locations VALUES (11, NULL, N' باخرز')
INSERT INTO dbo.Locations VALUES (11, NULL, N' بجستان')
INSERT INTO dbo.Locations VALUES (11, NULL, N' بردسکن')
INSERT INTO dbo.Locations VALUES (11, NULL, N' بینالود')
INSERT INTO dbo.Locations VALUES (11, NULL, N' تایباد')
INSERT INTO dbo.Locations VALUES (11, NULL, N' تربت جام')
INSERT INTO dbo.Locations VALUES (11, NULL, N' تربت حیدریه')
INSERT INTO dbo.Locations VALUES (11, NULL, N' جغتای')
INSERT INTO dbo.Locations VALUES (11, NULL, N' جوین')
INSERT INTO dbo.Locations VALUES (11, NULL, N' چناران')
INSERT INTO dbo.Locations VALUES (11, NULL, N' خلیل آباد')
INSERT INTO dbo.Locations VALUES (11, NULL, N' خواف')
INSERT INTO dbo.Locations VALUES (11, NULL, N' خوشاب')
INSERT INTO dbo.Locations VALUES (11, NULL, N' داورزن')
INSERT INTO dbo.Locations VALUES (11, NULL, N' درگز')
INSERT INTO dbo.Locations VALUES (11, NULL, N' رشتخوار')
INSERT INTO dbo.Locations VALUES (11, NULL, N' زاوه')
INSERT INTO dbo.Locations VALUES (11, NULL, N' سبزوار')
INSERT INTO dbo.Locations VALUES (11, NULL, N' سرخس')
INSERT INTO dbo.Locations VALUES (11, NULL, N' فریمان')
INSERT INTO dbo.Locations VALUES (11, NULL, N' فیروزه')
INSERT INTO dbo.Locations VALUES (11, NULL, N' قوچان')
INSERT INTO dbo.Locations VALUES (11, NULL, N' کاشمر')
INSERT INTO dbo.Locations VALUES (11, NULL, N' کلات')
INSERT INTO dbo.Locations VALUES (11, NULL, N' گناباد')
INSERT INTO dbo.Locations VALUES (11, NULL, N' مشهد')
INSERT INTO dbo.Locations VALUES (11, NULL, N' مه ولات')
INSERT INTO dbo.Locations VALUES (11, NULL, N' نیشابور')
INSERT INTO dbo.Locations VALUES (12, NULL, N' اسفراین')
INSERT INTO dbo.Locations VALUES (12, NULL, N' بجنورد')
INSERT INTO dbo.Locations VALUES (12, NULL, N' جاجرم')
INSERT INTO dbo.Locations VALUES (12, NULL, N' راز و جرگلان')
INSERT INTO dbo.Locations VALUES (12, NULL, N' شیروان')
INSERT INTO dbo.Locations VALUES (12, NULL, N' فاروج')
INSERT INTO dbo.Locations VALUES (12, NULL, N' گرمه')
INSERT INTO dbo.Locations VALUES (12, NULL, N' مانه وسملقان')
INSERT INTO dbo.Locations VALUES (13, NULL, N' آبادان')
INSERT INTO dbo.Locations VALUES (13, NULL, N' آغاجاری')
INSERT INTO dbo.Locations VALUES (13, NULL, N' امیدیه')
INSERT INTO dbo.Locations VALUES (13, NULL, N' اندیکا')
INSERT INTO dbo.Locations VALUES (13, NULL, N' اندیمشک')
INSERT INTO dbo.Locations VALUES (13, NULL, N' اهواز')
INSERT INTO dbo.Locations VALUES (13, NULL, N' ایذه')
INSERT INTO dbo.Locations VALUES (13, NULL, N' باغ ملک')
INSERT INTO dbo.Locations VALUES (13, NULL, N' باوی')
INSERT INTO dbo.Locations VALUES (13, NULL, N' بندرماهشهر')
INSERT INTO dbo.Locations VALUES (13, NULL, N' بهبهان')
INSERT INTO dbo.Locations VALUES (13, NULL, N' حمیدیه')
INSERT INTO dbo.Locations VALUES (13, NULL, N' خرمشهر')
INSERT INTO dbo.Locations VALUES (13, NULL, N' دزفول')
INSERT INTO dbo.Locations VALUES (13, NULL, N' دشت آزادگان')
INSERT INTO dbo.Locations VALUES (13, NULL, N' رامشیر')
INSERT INTO dbo.Locations VALUES (13, NULL, N' رامهرمز')
INSERT INTO dbo.Locations VALUES (13, NULL, N' شادگان')
INSERT INTO dbo.Locations VALUES (13, NULL, N' شوش')
INSERT INTO dbo.Locations VALUES (13, NULL, N' شوشتر')
INSERT INTO dbo.Locations VALUES (13, NULL, N' کارون')
INSERT INTO dbo.Locations VALUES (13, NULL, N' گتوند')
INSERT INTO dbo.Locations VALUES (13, NULL, N' لالی')
INSERT INTO dbo.Locations VALUES (13, NULL, N' مسجدسلیمان')
INSERT INTO dbo.Locations VALUES (13, NULL, N' هفتگل')
INSERT INTO dbo.Locations VALUES (13, NULL, N' هندیجان')
INSERT INTO dbo.Locations VALUES (13, NULL, N' هویزه')
INSERT INTO dbo.Locations VALUES (14, NULL, N' ابهر')
INSERT INTO dbo.Locations VALUES (14, NULL, N' ایجرود')
INSERT INTO dbo.Locations VALUES (14, NULL, N' خدابنده')
INSERT INTO dbo.Locations VALUES (14, NULL, N' خرمدره')
INSERT INTO dbo.Locations VALUES (14, NULL, N' زنجان')
INSERT INTO dbo.Locations VALUES (14, NULL, N' سلطانیه')
INSERT INTO dbo.Locations VALUES (14, NULL, N' طارم')
INSERT INTO dbo.Locations VALUES (14, NULL, N' ماهنشان')
INSERT INTO dbo.Locations VALUES (15, NULL, N' آرادان')
INSERT INTO dbo.Locations VALUES (15, NULL, N' دامغان')
INSERT INTO dbo.Locations VALUES (15, NULL, N' سرخه')
INSERT INTO dbo.Locations VALUES (15, NULL, N' سمنان')
INSERT INTO dbo.Locations VALUES (15, NULL, N' شاهرود')
INSERT INTO dbo.Locations VALUES (15, NULL, N' گرمسار')
INSERT INTO dbo.Locations VALUES (15, NULL, N' مهدی شهر')
INSERT INTO dbo.Locations VALUES (15, NULL, N' میامی')
INSERT INTO dbo.Locations VALUES (16, NULL, N' ایرانشهر')
INSERT INTO dbo.Locations VALUES (16, NULL, N' چابهار')
INSERT INTO dbo.Locations VALUES (16, NULL, N' خاش')
INSERT INTO dbo.Locations VALUES (16, NULL, N' دلگان')
INSERT INTO dbo.Locations VALUES (16, NULL, N' زابل')
INSERT INTO dbo.Locations VALUES (16, NULL, N' زاهدان')
INSERT INTO dbo.Locations VALUES (16, NULL, N' زهک')
INSERT INTO dbo.Locations VALUES (16, NULL, N' سراوان')
INSERT INTO dbo.Locations VALUES (16, NULL, N' سرباز')
INSERT INTO dbo.Locations VALUES (16, NULL, N' سیب و سوران')
INSERT INTO dbo.Locations VALUES (16, NULL, N' فنوج')
INSERT INTO dbo.Locations VALUES (16, NULL, N' قصرقند')
INSERT INTO dbo.Locations VALUES (16, NULL, N' کنارک')
INSERT INTO dbo.Locations VALUES (16, NULL, N' مهرستان')
INSERT INTO dbo.Locations VALUES (16, NULL, N' میرجاوه')
INSERT INTO dbo.Locations VALUES (16, NULL, N' نیک شهر')
INSERT INTO dbo.Locations VALUES (16, NULL, N' نیمروز')
INSERT INTO dbo.Locations VALUES (16, NULL, N' هامون')
INSERT INTO dbo.Locations VALUES (16, NULL, N' هیرمند')
INSERT INTO dbo.Locations VALUES (17, NULL, N' آباده')
INSERT INTO dbo.Locations VALUES (17, NULL, N' ارسنجان')
INSERT INTO dbo.Locations VALUES (17, NULL, N' استهبان')
INSERT INTO dbo.Locations VALUES (17, NULL, N' اقلید')
INSERT INTO dbo.Locations VALUES (17, NULL, N' بوانات')
INSERT INTO dbo.Locations VALUES (17, NULL, N' پاسارگاد')
INSERT INTO dbo.Locations VALUES (17, NULL, N' جهرم')
INSERT INTO dbo.Locations VALUES (17, NULL, N' خرامه')
INSERT INTO dbo.Locations VALUES (17, NULL, N' خرم بید')
INSERT INTO dbo.Locations VALUES (17, NULL, N' خنج')
INSERT INTO dbo.Locations VALUES (17, NULL, N' داراب')
INSERT INTO dbo.Locations VALUES (17, NULL, N' رستم')
INSERT INTO dbo.Locations VALUES (17, NULL, N' زرین دشت')
INSERT INTO dbo.Locations VALUES (17, NULL, N' سپیدان')
INSERT INTO dbo.Locations VALUES (17, NULL, N' سروستان')
INSERT INTO dbo.Locations VALUES (17, NULL, N' شیراز')
INSERT INTO dbo.Locations VALUES (17, NULL, N' فراشبند')
INSERT INTO dbo.Locations VALUES (17, NULL, N' فسا')
INSERT INTO dbo.Locations VALUES (17, NULL, N' فیروزآباد')
INSERT INTO dbo.Locations VALUES (17, NULL, N' قیروکارزین')
INSERT INTO dbo.Locations VALUES (17, NULL, N' کازرون')
INSERT INTO dbo.Locations VALUES (17, NULL, N' کوار')
INSERT INTO dbo.Locations VALUES (17, NULL, N' گراش')
INSERT INTO dbo.Locations VALUES (17, NULL, N' لارستان')
INSERT INTO dbo.Locations VALUES (17, NULL, N' لامرد')
INSERT INTO dbo.Locations VALUES (17, NULL, N' مرودشت')
INSERT INTO dbo.Locations VALUES (17, NULL, N' ممسنی')
INSERT INTO dbo.Locations VALUES (17, NULL, N' مهر')
INSERT INTO dbo.Locations VALUES (17, NULL, N' نی ریز')
INSERT INTO dbo.Locations VALUES (18, NULL, N' آبیک')
INSERT INTO dbo.Locations VALUES (18, NULL, N' آوج')
INSERT INTO dbo.Locations VALUES (18, NULL, N' البرز')
INSERT INTO dbo.Locations VALUES (18, NULL, N' بویین زهرا')
INSERT INTO dbo.Locations VALUES (18, NULL, N' تاکستان')
INSERT INTO dbo.Locations VALUES (18, NULL, N' قزوین')
INSERT INTO dbo.Locations VALUES (19, NULL, N' قم')
INSERT INTO dbo.Locations VALUES (20, NULL, N' بانه')
INSERT INTO dbo.Locations VALUES (20, NULL, N' بیجار')
INSERT INTO dbo.Locations VALUES (20, NULL, N' دهگلان')
INSERT INTO dbo.Locations VALUES (20, NULL, N' دیواندره')
INSERT INTO dbo.Locations VALUES (20, NULL, N' سروآباد')
INSERT INTO dbo.Locations VALUES (20, NULL, N' سقز')
INSERT INTO dbo.Locations VALUES (20, NULL, N' سنندج')
INSERT INTO dbo.Locations VALUES (20, NULL, N' قروه')
INSERT INTO dbo.Locations VALUES (20, NULL, N' کامیاران')
INSERT INTO dbo.Locations VALUES (20, NULL, N' مریوان')
INSERT INTO dbo.Locations VALUES (21, NULL, N' ارزوییه')
INSERT INTO dbo.Locations VALUES (21, NULL, N' انار')
INSERT INTO dbo.Locations VALUES (21, NULL, N' بافت')
INSERT INTO dbo.Locations VALUES (21, NULL, N' بردسیر')
INSERT INTO dbo.Locations VALUES (21, NULL, N' بم')
INSERT INTO dbo.Locations VALUES (21, NULL, N' جیرفت')
INSERT INTO dbo.Locations VALUES (21, NULL, N' رابر')
INSERT INTO dbo.Locations VALUES (21, NULL, N' راور')
INSERT INTO dbo.Locations VALUES (21, NULL, N' رفسنجان')
INSERT INTO dbo.Locations VALUES (21, NULL, N' رودبارجنوب')
INSERT INTO dbo.Locations VALUES (21, NULL, N' ریگان')
INSERT INTO dbo.Locations VALUES (21, NULL, N' زرند')
INSERT INTO dbo.Locations VALUES (21, NULL, N' سیرجان')
INSERT INTO dbo.Locations VALUES (21, NULL, N' شهربابک')
INSERT INTO dbo.Locations VALUES (21, NULL, N' عنبرآباد')
INSERT INTO dbo.Locations VALUES (21, NULL, N' فاریاب')
INSERT INTO dbo.Locations VALUES (21, NULL, N' فهرج')
INSERT INTO dbo.Locations VALUES (21, NULL, N' قلعه گنج')
INSERT INTO dbo.Locations VALUES (21, NULL, N' کرمان')
INSERT INTO dbo.Locations VALUES (21, NULL, N' کوهبنان')
INSERT INTO dbo.Locations VALUES (21, NULL, N' کهنوج')
INSERT INTO dbo.Locations VALUES (21, NULL, N' منوجان')
INSERT INTO dbo.Locations VALUES (21, NULL, N' نرماشیر')
INSERT INTO dbo.Locations VALUES (22, NULL, N' اسلام آبادغرب')
INSERT INTO dbo.Locations VALUES (22, NULL, N' پاوه')
INSERT INTO dbo.Locations VALUES (22, NULL, N' ثلاث باباجانی')
INSERT INTO dbo.Locations VALUES (22, NULL, N' جوانرود')
INSERT INTO dbo.Locations VALUES (22, NULL, N' دالاهو')
INSERT INTO dbo.Locations VALUES (22, NULL, N' روانسر')
INSERT INTO dbo.Locations VALUES (22, NULL, N' سرپل ذهاب')
INSERT INTO dbo.Locations VALUES (22, NULL, N' سنقر')
INSERT INTO dbo.Locations VALUES (22, NULL, N' صحنه')
INSERT INTO dbo.Locations VALUES (22, NULL, N' قصرشیرین')
INSERT INTO dbo.Locations VALUES (22, NULL, N' کرمانشاه')
INSERT INTO dbo.Locations VALUES (22, NULL, N' کنگاور')
INSERT INTO dbo.Locations VALUES (22, NULL, N' گیلانغرب')
INSERT INTO dbo.Locations VALUES (22, NULL, N' هرسین')
INSERT INTO dbo.Locations VALUES (23, NULL, N' باشت')
INSERT INTO dbo.Locations VALUES (23, NULL, N' بویراحمد')
INSERT INTO dbo.Locations VALUES (23, NULL, N' بهمیی')
INSERT INTO dbo.Locations VALUES (23, NULL, N' چرام')
INSERT INTO dbo.Locations VALUES (23, NULL, N' دنا')
INSERT INTO dbo.Locations VALUES (23, NULL, N' کهگیلویه')
INSERT INTO dbo.Locations VALUES (23, NULL, N' گچساران')
INSERT INTO dbo.Locations VALUES (23, NULL, N' لنده')
INSERT INTO dbo.Locations VALUES (24, NULL, N' آزادشهر')
INSERT INTO dbo.Locations VALUES (24, NULL, N' آق قلا')
INSERT INTO dbo.Locations VALUES (24, NULL, N' بندرگز')
INSERT INTO dbo.Locations VALUES (24, NULL, N' ترکمن')
INSERT INTO dbo.Locations VALUES (24, NULL, N' رامیان')
INSERT INTO dbo.Locations VALUES (24, NULL, N' علی آباد')
INSERT INTO dbo.Locations VALUES (24, NULL, N' کردکوی')
INSERT INTO dbo.Locations VALUES (24, NULL, N' کلاله')
INSERT INTO dbo.Locations VALUES (24, NULL, N' گالیکش')
INSERT INTO dbo.Locations VALUES (24, NULL, N' گرگان')
INSERT INTO dbo.Locations VALUES (24, NULL, N' گمیشان')
INSERT INTO dbo.Locations VALUES (24, NULL, N' گنبدکاووس')
INSERT INTO dbo.Locations VALUES (24, NULL, N' مراوه تپه')
INSERT INTO dbo.Locations VALUES (24, NULL, N' مینودشت')
INSERT INTO dbo.Locations VALUES (25, NULL, N' آستارا')
INSERT INTO dbo.Locations VALUES (25, NULL, N' آستانه اشرفیه')
INSERT INTO dbo.Locations VALUES (25, NULL, N' املش')
INSERT INTO dbo.Locations VALUES (25, NULL, N' بندرانزلی')
INSERT INTO dbo.Locations VALUES (25, NULL, N' رشت')
INSERT INTO dbo.Locations VALUES (25, NULL, N' رضوانشهر')
INSERT INTO dbo.Locations VALUES (25, NULL, N' رودبار')
INSERT INTO dbo.Locations VALUES (25, NULL, N' رودسر')
INSERT INTO dbo.Locations VALUES (25, NULL, N' سیاهکل')
INSERT INTO dbo.Locations VALUES (25, NULL, N' شفت')
INSERT INTO dbo.Locations VALUES (25, NULL, N' صومعه سرا')
INSERT INTO dbo.Locations VALUES (25, NULL, N' طوالش')
INSERT INTO dbo.Locations VALUES (25, NULL, N' فومن')
INSERT INTO dbo.Locations VALUES (25, NULL, N' لاهیجان')
INSERT INTO dbo.Locations VALUES (25, NULL, N' لنگرود')
INSERT INTO dbo.Locations VALUES (25, NULL, N' ماسال')
INSERT INTO dbo.Locations VALUES (26, NULL, N' ازنا')
INSERT INTO dbo.Locations VALUES (26, NULL, N' الیگودرز')
INSERT INTO dbo.Locations VALUES (26, NULL, N' بروجرد')
INSERT INTO dbo.Locations VALUES (26, NULL, N' پلدختر')
INSERT INTO dbo.Locations VALUES (26, NULL, N' خرم آباد')
INSERT INTO dbo.Locations VALUES (26, NULL, N' دلفان')
INSERT INTO dbo.Locations VALUES (26, NULL, N' دورود')
INSERT INTO dbo.Locations VALUES (26, NULL, N' دوره')
INSERT INTO dbo.Locations VALUES (26, NULL, N' رومشکان')
INSERT INTO dbo.Locations VALUES (26, NULL, N' سلسله')
INSERT INTO dbo.Locations VALUES (26, NULL, N' کوهدشت')
INSERT INTO dbo.Locations VALUES (27, NULL, N' آمل')
INSERT INTO dbo.Locations VALUES (27, NULL, N' بابل')
INSERT INTO dbo.Locations VALUES (27, NULL, N' بابلسر')
INSERT INTO dbo.Locations VALUES (27, NULL, N' بهشهر')
INSERT INTO dbo.Locations VALUES (27, NULL, N' تنکابن')
INSERT INTO dbo.Locations VALUES (27, NULL, N' جویبار')
INSERT INTO dbo.Locations VALUES (27, NULL, N' چالوس')
INSERT INTO dbo.Locations VALUES (27, NULL, N' رامسر')
INSERT INTO dbo.Locations VALUES (27, NULL, N' ساری')
INSERT INTO dbo.Locations VALUES (27, NULL, N' سوادکوه')
INSERT INTO dbo.Locations VALUES (27, NULL, N' سوادکوه شمالی')
INSERT INTO dbo.Locations VALUES (27, NULL, N' سیمرغ')
INSERT INTO dbo.Locations VALUES (27, NULL, N' عباس آباد')
INSERT INTO dbo.Locations VALUES (27, NULL, N' فریدونکنار')
INSERT INTO dbo.Locations VALUES (27, NULL, N' قایم شهر')
INSERT INTO dbo.Locations VALUES (27, NULL, N' کلاردشت')
INSERT INTO dbo.Locations VALUES (27, NULL, N' گلوگاه')
INSERT INTO dbo.Locations VALUES (27, NULL, N' محمودآباد')
INSERT INTO dbo.Locations VALUES (27, NULL, N' میاندورود')
INSERT INTO dbo.Locations VALUES (27, NULL, N' نکا')
INSERT INTO dbo.Locations VALUES (27, NULL, N' نور')
INSERT INTO dbo.Locations VALUES (27, NULL, N' نوشهر')
INSERT INTO dbo.Locations VALUES (28, NULL, N' آشتیان')
INSERT INTO dbo.Locations VALUES (28, NULL, N' اراک')
INSERT INTO dbo.Locations VALUES (28, NULL, N' تفرش')
INSERT INTO dbo.Locations VALUES (28, NULL, N' خمین')
INSERT INTO dbo.Locations VALUES (28, NULL, N' خنداب')
INSERT INTO dbo.Locations VALUES (28, NULL, N' دلیجان')
INSERT INTO dbo.Locations VALUES (28, NULL, N' زرندیه')
INSERT INTO dbo.Locations VALUES (28, NULL, N' ساوه')
INSERT INTO dbo.Locations VALUES (28, NULL, N' شازند')
INSERT INTO dbo.Locations VALUES (28, NULL, N' فراهان')
INSERT INTO dbo.Locations VALUES (28, NULL, N' کمیجان')
INSERT INTO dbo.Locations VALUES (28, NULL, N' محلات')
INSERT INTO dbo.Locations VALUES (29, NULL, N' ابوموسی')
INSERT INTO dbo.Locations VALUES (29, NULL, N' بستک')
INSERT INTO dbo.Locations VALUES (29, NULL, N' بشاگرد')
INSERT INTO dbo.Locations VALUES (29, NULL, N' بندرعباس')
INSERT INTO dbo.Locations VALUES (29, NULL, N' بندرلنگه')
INSERT INTO dbo.Locations VALUES (29, NULL, N' پارسیان')
INSERT INTO dbo.Locations VALUES (29, NULL, N' جاسک')
INSERT INTO dbo.Locations VALUES (29, NULL, N' حاجی اباد')
INSERT INTO dbo.Locations VALUES (29, NULL, N' خمیر')
INSERT INTO dbo.Locations VALUES (29, NULL, N' رودان')
INSERT INTO dbo.Locations VALUES (29, NULL, N' سیریک')
INSERT INTO dbo.Locations VALUES (29, NULL, N' قشم')
INSERT INTO dbo.Locations VALUES (29, NULL, N' میناب')
INSERT INTO dbo.Locations VALUES (30, NULL, N' اسدآباد')
INSERT INTO dbo.Locations VALUES (30, NULL, N' بهار')
INSERT INTO dbo.Locations VALUES (30, NULL, N' تویسرکان')
INSERT INTO dbo.Locations VALUES (30, NULL, N' رزن')
INSERT INTO dbo.Locations VALUES (30, NULL, N' فامنین')
INSERT INTO dbo.Locations VALUES (30, NULL, N' کبودرآهنگ')
INSERT INTO dbo.Locations VALUES (30, NULL, N' ملایر')
INSERT INTO dbo.Locations VALUES (30, NULL, N' نهاوند')
INSERT INTO dbo.Locations VALUES (30, NULL, N' همدان')
INSERT INTO dbo.Locations VALUES (31, NULL, N' ابرکوه')
INSERT INTO dbo.Locations VALUES (31, NULL, N' اردکان')
INSERT INTO dbo.Locations VALUES (31, NULL, N' اشکذر')
INSERT INTO dbo.Locations VALUES (31, NULL, N' بافق')
INSERT INTO dbo.Locations VALUES (31, NULL, N' بهاباد')
INSERT INTO dbo.Locations VALUES (31, NULL, N' تفت')
INSERT INTO dbo.Locations VALUES (31, NULL, N' خاتم')
INSERT INTO dbo.Locations VALUES (31, NULL, N' مهریز')
INSERT INTO dbo.Locations VALUES (31, NULL, N' میبد')
INSERT INTO dbo.Locations VALUES (31, NULL, N' یزد')
INSERT INTO dbo.Locations VALUES (1, 32, N' آذرشهر')
INSERT INTO dbo.Locations VALUES (1, 32, N' تیمورلو')
INSERT INTO dbo.Locations VALUES (1, 32, N' گوگان')
INSERT INTO dbo.Locations VALUES (1, 32, N' ممقان')
INSERT INTO dbo.Locations VALUES (1, 33, N' اسکو')
INSERT INTO dbo.Locations VALUES (1, 33, N' ایلخچی')
INSERT INTO dbo.Locations VALUES (1, 33, N' سهند')
INSERT INTO dbo.Locations VALUES (1, 34, N' اهر')
INSERT INTO dbo.Locations VALUES (1, 34, N' هوراند')
INSERT INTO dbo.Locations VALUES (1, 35, N' بستان آباد')
INSERT INTO dbo.Locations VALUES (1, 35, N' تیکمه داش')
INSERT INTO dbo.Locations VALUES (1, 36, N' بناب')
INSERT INTO dbo.Locations VALUES (1, 37, N' باسمنج')
INSERT INTO dbo.Locations VALUES (1, 37, N' تبریز')
INSERT INTO dbo.Locations VALUES (1, 37, N' خسروشاه')
INSERT INTO dbo.Locations VALUES (1, 37, N' سردرود')
INSERT INTO dbo.Locations VALUES (1, 38, N' جلفا')
INSERT INTO dbo.Locations VALUES (1, 38, N' سیه رود')
INSERT INTO dbo.Locations VALUES (1, 38, N' هادیشهر')
INSERT INTO dbo.Locations VALUES (1, 39, N' قره آغاج')
INSERT INTO dbo.Locations VALUES (1, 40, N' خمارلو')
INSERT INTO dbo.Locations VALUES (1, 41, N' دوزدوزان')
INSERT INTO dbo.Locations VALUES (1, 41, N' سراب')
INSERT INTO dbo.Locations VALUES (1, 41, N' شربیان')
INSERT INTO dbo.Locations VALUES (1, 41, N' مهربان')
INSERT INTO dbo.Locations VALUES (1, 42, N' تسوج')
INSERT INTO dbo.Locations VALUES (1, 42, N' خامنه')
INSERT INTO dbo.Locations VALUES (1, 42, N' سیس')
INSERT INTO dbo.Locations VALUES (1, 42, N' شبستر')
INSERT INTO dbo.Locations VALUES (1, 42, N' شرفخانه')
INSERT INTO dbo.Locations VALUES (1, 42, N' شندآباد')
INSERT INTO dbo.Locations VALUES (1, 42, N' صوفیان')
INSERT INTO dbo.Locations VALUES (1, 42, N' کوزه کنان')
INSERT INTO dbo.Locations VALUES (1, 42, N' وایقان')
INSERT INTO dbo.Locations VALUES (1, 43, N' جوان قلعه')
INSERT INTO dbo.Locations VALUES (1, 43, N' عجب شیر')
INSERT INTO dbo.Locations VALUES (1, 44, N' آبش احمد')
INSERT INTO dbo.Locations VALUES (1, 44, N' کلیبر')
INSERT INTO dbo.Locations VALUES (1, 45, N' خداجوخراجو)')
INSERT INTO dbo.Locations VALUES (1, 45, N' مراغه')
INSERT INTO dbo.Locations VALUES (1, 46, N' بناب مرند')
INSERT INTO dbo.Locations VALUES (1, 46, N' زنوز')
INSERT INTO dbo.Locations VALUES (1, 46, N' کشکسرای')
INSERT INTO dbo.Locations VALUES (1, 46, N' مرند')
INSERT INTO dbo.Locations VALUES (1, 46, N' یامچی')
INSERT INTO dbo.Locations VALUES (1, 47, N' لیلان')
INSERT INTO dbo.Locations VALUES (1, 47, N' مبارک شهر')
INSERT INTO dbo.Locations VALUES (1, 47, N' ملکان')
INSERT INTO dbo.Locations VALUES (1, 48, N' آقکند')
INSERT INTO dbo.Locations VALUES (1, 48, N' اچاچی')
INSERT INTO dbo.Locations VALUES (1, 48, N' ترک')
INSERT INTO dbo.Locations VALUES (1, 48, N' ترکمانچای')
INSERT INTO dbo.Locations VALUES (1, 48, N' میانه')
INSERT INTO dbo.Locations VALUES (1, 49, N' خاروانا')
INSERT INTO dbo.Locations VALUES (1, 49, N' ورزقان')
INSERT INTO dbo.Locations VALUES (1, 50, N' بخشایش')
INSERT INTO dbo.Locations VALUES (1, 50, N' خواجه')
INSERT INTO dbo.Locations VALUES (1, 50, N' زرنق')
INSERT INTO dbo.Locations VALUES (1, 50, N' کلوانق')
INSERT INTO dbo.Locations VALUES (1, 50, N' هریس')
INSERT INTO dbo.Locations VALUES (1, 51, N' نظرکهریزی')
INSERT INTO dbo.Locations VALUES (1, 51, N' هشترود')
INSERT INTO dbo.Locations VALUES (2, 52, N' ارومیه')
INSERT INTO dbo.Locations VALUES (2, 52, N' سرو')
INSERT INTO dbo.Locations VALUES (2, 52, N' سیلوانه')
INSERT INTO dbo.Locations VALUES (2, 52, N' قوشچی')
INSERT INTO dbo.Locations VALUES (2, 52, N' نوشین')
INSERT INTO dbo.Locations VALUES (2, 53, N' اشنویه')
INSERT INTO dbo.Locations VALUES (2, 53, N' نالوس')
INSERT INTO dbo.Locations VALUES (2, 54, N' بوکان')
INSERT INTO dbo.Locations VALUES (2, 54, N' سیمینه')
INSERT INTO dbo.Locations VALUES (2, 55, N' پلدشت')
INSERT INTO dbo.Locations VALUES (2, 55, N' نازک علیا')
INSERT INTO dbo.Locations VALUES (2, 56, N' پیرانشهر')
INSERT INTO dbo.Locations VALUES (2, 56, N' گردکشانه')
INSERT INTO dbo.Locations VALUES (2, 57, N' تکاب')
INSERT INTO dbo.Locations VALUES (2, 58, N' آواجیق')
INSERT INTO dbo.Locations VALUES (2, 58, N' سیه چشمه')
INSERT INTO dbo.Locations VALUES (2, 59, N' قره ضیاءالدین')
INSERT INTO dbo.Locations VALUES (2, 60, N' ایواوغلی')
INSERT INTO dbo.Locations VALUES (2, 60, N' خوی')
INSERT INTO dbo.Locations VALUES (2, 60, N' دیزج دیز')
INSERT INTO dbo.Locations VALUES (2, 60, N' زرآباد')
INSERT INTO dbo.Locations VALUES (2, 60, N' فیرورق')
INSERT INTO dbo.Locations VALUES (2, 60, N' قطور')
INSERT INTO dbo.Locations VALUES (2, 61, N' ربط')
INSERT INTO dbo.Locations VALUES (2, 61, N' سردشت')
INSERT INTO dbo.Locations VALUES (2, 61, N' میرآباد')
INSERT INTO dbo.Locations VALUES (2, 62, N' تازه شهر')
INSERT INTO dbo.Locations VALUES (2, 62, N' سلماس')
INSERT INTO dbo.Locations VALUES (2, 63, N' شاهین دژ')
INSERT INTO dbo.Locations VALUES (2, 63, N' کشاورز')
INSERT INTO dbo.Locations VALUES (2, 63, N' محمودآباد')
INSERT INTO dbo.Locations VALUES (2, 64, N' شوط')
INSERT INTO dbo.Locations VALUES (2, 64, N' مرگنلر')
INSERT INTO dbo.Locations VALUES (2, 65, N' بازرگان')
INSERT INTO dbo.Locations VALUES (2, 65, N' ماکو')
INSERT INTO dbo.Locations VALUES (2, 66, N' خلیفان')
INSERT INTO dbo.Locations VALUES (2, 66, N' مهاباد')
INSERT INTO dbo.Locations VALUES (2, 67, N' باروق')
INSERT INTO dbo.Locations VALUES (2, 67, N' چهاربرج')
INSERT INTO dbo.Locations VALUES (2, 67, N' میاندوآب')
INSERT INTO dbo.Locations VALUES (2, 68, N' محمدیار')
INSERT INTO dbo.Locations VALUES (2, 68, N' نقده')
INSERT INTO dbo.Locations VALUES (3, 69, N' اردبیل')
INSERT INTO dbo.Locations VALUES (3, 69, N' هیر')
INSERT INTO dbo.Locations VALUES (3, 70, N' بیله سوار')
INSERT INTO dbo.Locations VALUES (3, 70, N' جعفرآباد')
INSERT INTO dbo.Locations VALUES (3, 71, N' اسلام اباد')
INSERT INTO dbo.Locations VALUES (3, 71, N' اصلاندوز')
INSERT INTO dbo.Locations VALUES (3, 71, N' پارس آباد')
INSERT INTO dbo.Locations VALUES (3, 71, N' تازه کند')
INSERT INTO dbo.Locations VALUES (3, 72, N' خلخال')
INSERT INTO dbo.Locations VALUES (3, 72, N' کلور')
INSERT INTO dbo.Locations VALUES (3, 72, N' هشتجین')
INSERT INTO dbo.Locations VALUES (3, 73, N' سرعین')
INSERT INTO dbo.Locations VALUES (3, 74, N' گیوی')
INSERT INTO dbo.Locations VALUES (3, 75, N' تازه کندانگوت')
INSERT INTO dbo.Locations VALUES (3, 75, N' گرمی')
INSERT INTO dbo.Locations VALUES (3, 76, N' رضی')
INSERT INTO dbo.Locations VALUES (3, 76, N' فخراباد')
INSERT INTO dbo.Locations VALUES (3, 76, N' قصابه')
INSERT INTO dbo.Locations VALUES (3, 76, N' لاهرود')
INSERT INTO dbo.Locations VALUES (3, 76, N' مرادلو')
INSERT INTO dbo.Locations VALUES (3, 76, N' مشگین شهر')
INSERT INTO dbo.Locations VALUES (3, 77, N' آبی بیگلو')
INSERT INTO dbo.Locations VALUES (3, 77, N' عنبران')
INSERT INTO dbo.Locations VALUES (3, 77, N' نمین')
INSERT INTO dbo.Locations VALUES (3, 78, N' کوراییم')
INSERT INTO dbo.Locations VALUES (3, 78, N' نیر')
INSERT INTO dbo.Locations VALUES (4, 79, N' آران وبیدگل')
INSERT INTO dbo.Locations VALUES (4, 79, N' ابوزیدآباد')
INSERT INTO dbo.Locations VALUES (4, 79, N' سفیدشهر')
INSERT INTO dbo.Locations VALUES (4, 79, N' نوش آباد')
INSERT INTO dbo.Locations VALUES (4, 80, N' اردستان')
INSERT INTO dbo.Locations VALUES (4, 80, N' زواره')
INSERT INTO dbo.Locations VALUES (4, 80, N' مهاباد')
INSERT INTO dbo.Locations VALUES (4, 81, N' اژیه')
INSERT INTO dbo.Locations VALUES (4, 81, N' اصفهان')
INSERT INTO dbo.Locations VALUES (4, 81, N' بهارستان')
INSERT INTO dbo.Locations VALUES (4, 81, N' تودشک')
INSERT INTO dbo.Locations VALUES (4, 81, N' حسن اباد')
INSERT INTO dbo.Locations VALUES (4, 81, N' زیار')
INSERT INTO dbo.Locations VALUES (4, 81, N' سجزی')
INSERT INTO dbo.Locations VALUES (4, 81, N' قهجاورستان')
INSERT INTO dbo.Locations VALUES (4, 81, N' کوهپایه')
INSERT INTO dbo.Locations VALUES (4, 81, N' محمدآباد')
INSERT INTO dbo.Locations VALUES (4, 81, N' نصرآباد')
INSERT INTO dbo.Locations VALUES (4, 81, N' نیک آباد')
INSERT INTO dbo.Locations VALUES (4, 81, N' ورزنه')
INSERT INTO dbo.Locations VALUES (4, 81, N' هرند')
INSERT INTO dbo.Locations VALUES (4, 82, N' حبیب آباد')
INSERT INTO dbo.Locations VALUES (4, 82, N' خورزوق')
INSERT INTO dbo.Locations VALUES (4, 82, N' دستگرد')
INSERT INTO dbo.Locations VALUES (4, 82, N' دولت آباد')
INSERT INTO dbo.Locations VALUES (4, 82, N' سین')
INSERT INTO dbo.Locations VALUES (4, 82, N' شاپورآباد')
INSERT INTO dbo.Locations VALUES (4, 82, N' کمشچه')
INSERT INTO dbo.Locations VALUES (4, 83, N' افوس')
INSERT INTO dbo.Locations VALUES (4, 83, N' بویین ومیاندشت')
INSERT INTO dbo.Locations VALUES (4, 84, N' تیران')
INSERT INTO dbo.Locations VALUES (4, 84, N' رضوانشهر')
INSERT INTO dbo.Locations VALUES (4, 84, N' عسگران')
INSERT INTO dbo.Locations VALUES (4, 85, N' چادگان')
INSERT INTO dbo.Locations VALUES (4, 85, N' رزوه')
INSERT INTO dbo.Locations VALUES (4, 86, N' اصغرآباد')
INSERT INTO dbo.Locations VALUES (4, 86, N' خمینی شهر')
INSERT INTO dbo.Locations VALUES (4, 86, N' درچه')
INSERT INTO dbo.Locations VALUES (4, 86, N' کوشک')
INSERT INTO dbo.Locations VALUES (4, 87, N' خوانسار')
INSERT INTO dbo.Locations VALUES (4, 88, N' جندق')
INSERT INTO dbo.Locations VALUES (4, 88, N' خور')
INSERT INTO dbo.Locations VALUES (4, 88, N' فرخی')
INSERT INTO dbo.Locations VALUES (4, 89, N' دهاقان')
INSERT INTO dbo.Locations VALUES (4, 89, N' گلشن')
INSERT INTO dbo.Locations VALUES (4, 90, N' حنا')
INSERT INTO dbo.Locations VALUES (4, 90, N' سمیرم')
INSERT INTO dbo.Locations VALUES (4, 90, N' کمه')
INSERT INTO dbo.Locations VALUES (4, 90, N' ونک')
INSERT INTO dbo.Locations VALUES (4, 91, N' شاهین شهر')
INSERT INTO dbo.Locations VALUES (4, 91, N' گرگاب')
INSERT INTO dbo.Locations VALUES (4, 91, N' گزبرخوار')
INSERT INTO dbo.Locations VALUES (4, 91, N' لای بید')
INSERT INTO dbo.Locations VALUES (4, 91, N' میمه')
INSERT INTO dbo.Locations VALUES (4, 91, N' وزوان')
INSERT INTO dbo.Locations VALUES (4, 92, N' شهرضا')
INSERT INTO dbo.Locations VALUES (4, 92, N' منظریه')
INSERT INTO dbo.Locations VALUES (4, 93, N' داران')
INSERT INTO dbo.Locations VALUES (4, 93, N' دامنه')
INSERT INTO dbo.Locations VALUES (4, 94, N' برف انبار')
INSERT INTO dbo.Locations VALUES (4, 94, N' فریدونشهر')
INSERT INTO dbo.Locations VALUES (4, 95, N' ابریشم')
INSERT INTO dbo.Locations VALUES (4, 95, N' ایمانشهر')
INSERT INTO dbo.Locations VALUES (4, 95, N' بهاران شهر')
INSERT INTO dbo.Locations VALUES (4, 95, N' پیربکران')
INSERT INTO dbo.Locations VALUES (4, 95, N' زازران')
INSERT INTO dbo.Locations VALUES (4, 95, N' فلاورجان')
INSERT INTO dbo.Locations VALUES (4, 95, N' قهدریجان')
INSERT INTO dbo.Locations VALUES (4, 95, N' کلیشادوسودرجان')
INSERT INTO dbo.Locations VALUES (4, 96, N' برزک')
INSERT INTO dbo.Locations VALUES (4, 96, N' جوشقان قالی')
INSERT INTO dbo.Locations VALUES (4, 96, N' قمصر')
INSERT INTO dbo.Locations VALUES (4, 96, N' کاشان')
INSERT INTO dbo.Locations VALUES (4, 96, N' کامو و چوگان')
INSERT INTO dbo.Locations VALUES (4, 96, N' مشکات')
INSERT INTO dbo.Locations VALUES (4, 96, N' نیاسر')
INSERT INTO dbo.Locations VALUES (4, 97, N' گلپایگان')
INSERT INTO dbo.Locations VALUES (4, 97, N' گلشهر')
INSERT INTO dbo.Locations VALUES (4, 97, N' گوگد')
INSERT INTO dbo.Locations VALUES (4, 98, N' باغ بهادران')
INSERT INTO dbo.Locations VALUES (4, 98, N' باغشاد')
INSERT INTO dbo.Locations VALUES (4, 98, N' چرمهین')
INSERT INTO dbo.Locations VALUES (4, 98, N' چمگردان')
INSERT INTO dbo.Locations VALUES (4, 98, N' زاینده رود')
INSERT INTO dbo.Locations VALUES (4, 98, N' زرین شهر')
INSERT INTO dbo.Locations VALUES (4, 98, N' سده لنجان')
INSERT INTO dbo.Locations VALUES (4, 98, N' فولادشهر')
INSERT INTO dbo.Locations VALUES (4, 98, N' ورنامخواست')
INSERT INTO dbo.Locations VALUES (4, 99, N' دیزیچه')
INSERT INTO dbo.Locations VALUES (4, 99, N' زیباشهر')
INSERT INTO dbo.Locations VALUES (4, 99, N' طالخونچه')
INSERT INTO dbo.Locations VALUES (4, 99, N' کرکوند')
INSERT INTO dbo.Locations VALUES (4, 99, N' مبارکه')
INSERT INTO dbo.Locations VALUES (4, 99, N' مجلسی')
INSERT INTO dbo.Locations VALUES (4, 100, N' انارک')
INSERT INTO dbo.Locations VALUES (4, 100, N' بافران')
INSERT INTO dbo.Locations VALUES (4, 100, N' نایین')
INSERT INTO dbo.Locations VALUES (4, 101, N' جوزدان')
INSERT INTO dbo.Locations VALUES (4, 101, N' دهق')
INSERT INTO dbo.Locations VALUES (4, 101, N' علویجه')
INSERT INTO dbo.Locations VALUES (4, 101, N' کهریزسنگ')
INSERT INTO dbo.Locations VALUES (4, 101, N' گلدشت')
INSERT INTO dbo.Locations VALUES (4, 101, N' نجف آباد')
INSERT INTO dbo.Locations VALUES (4, 102, N' بادرود')
INSERT INTO dbo.Locations VALUES (4, 102, N' خالدآباد')
INSERT INTO dbo.Locations VALUES (4, 102, N' طرق رود')
INSERT INTO dbo.Locations VALUES (4, 102, N' نطنز')
INSERT INTO dbo.Locations VALUES (5, 103, N' اشتهارد')
INSERT INTO dbo.Locations VALUES (5, 104, N' چهارباغ')
INSERT INTO dbo.Locations VALUES (5, 104, N' شهرجدیدهشتگرد')
INSERT INTO dbo.Locations VALUES (5, 104, N' کوهسار')
INSERT INTO dbo.Locations VALUES (5, 104, N' گلسار')
INSERT INTO dbo.Locations VALUES (5, 104, N' هشتگرد')
INSERT INTO dbo.Locations VALUES (5, 105, N' طالقان')
INSERT INTO dbo.Locations VALUES (5, 106, N' فردیس')
INSERT INTO dbo.Locations VALUES (5, 106, N' مشکین دشت')
INSERT INTO dbo.Locations VALUES (5, 107, N' آسارا')
INSERT INTO dbo.Locations VALUES (5, 107, N' کرج')
INSERT INTO dbo.Locations VALUES (5, 107, N' کمال شهر')
INSERT INTO dbo.Locations VALUES (5, 107, N' گرمدره')
INSERT INTO dbo.Locations VALUES (5, 107, N' ماهدشت')
INSERT INTO dbo.Locations VALUES (5, 107, N' محمدشهر')
INSERT INTO dbo.Locations VALUES (5, 108, N' تنکمان')
INSERT INTO dbo.Locations VALUES (5, 108, N' نظرآباد')
INSERT INTO dbo.Locations VALUES (6, 109, N' آبدانان')
INSERT INTO dbo.Locations VALUES (6, 109, N' سراب باغ')
INSERT INTO dbo.Locations VALUES (6, 109, N' مورموری')
INSERT INTO dbo.Locations VALUES (6, 110, N' ایلام')
INSERT INTO dbo.Locations VALUES (6, 110, N' چوار')
INSERT INTO dbo.Locations VALUES (6, 111, N' ایوان')
INSERT INTO dbo.Locations VALUES (6, 111, N' زرنه')
INSERT INTO dbo.Locations VALUES (6, 112, N' بدره')
INSERT INTO dbo.Locations VALUES (6, 113, N' آسمان آباد')
INSERT INTO dbo.Locations VALUES (6, 113, N' بلاوه')
INSERT INTO dbo.Locations VALUES (6, 113, N' توحید')
INSERT INTO dbo.Locations VALUES (6, 113, N' سرابله')
INSERT INTO dbo.Locations VALUES (6, 113, N' شباب')
INSERT INTO dbo.Locations VALUES (6, 114, N' دره شهر')
INSERT INTO dbo.Locations VALUES (6, 114, N' ماژین')
INSERT INTO dbo.Locations VALUES (6, 115, N' پهله')
INSERT INTO dbo.Locations VALUES (6, 115, N' دهلران')
INSERT INTO dbo.Locations VALUES (6, 115, N' موسیان')
INSERT INTO dbo.Locations VALUES (6, 115, N' میمه')
INSERT INTO dbo.Locations VALUES (6, 116, N' لومار')
INSERT INTO dbo.Locations VALUES (6, 117, N' ارکواز')
INSERT INTO dbo.Locations VALUES (6, 117, N' دلگشا')
INSERT INTO dbo.Locations VALUES (6, 117, N' مهر')
INSERT INTO dbo.Locations VALUES (6, 118, N' صالح آباد')
INSERT INTO dbo.Locations VALUES (6, 118, N' مهران')
INSERT INTO dbo.Locations VALUES (7, 119, N' بوشهر')
INSERT INTO dbo.Locations VALUES (7, 119, N' چغادک')
INSERT INTO dbo.Locations VALUES (7, 119, N' خارک')
INSERT INTO dbo.Locations VALUES (7, 119, N' عالی شهر')
INSERT INTO dbo.Locations VALUES (7, 120, N' آباد')
INSERT INTO dbo.Locations VALUES (7, 120, N' اهرم')
INSERT INTO dbo.Locations VALUES (7, 120, N' دلوار')
INSERT INTO dbo.Locations VALUES (7, 121, N' انارستان')
INSERT INTO dbo.Locations VALUES (7, 121, N' جم')
INSERT INTO dbo.Locations VALUES (7, 121, N' ریز')
INSERT INTO dbo.Locations VALUES (7, 122, N' آب پخش')
INSERT INTO dbo.Locations VALUES (7, 122, N' برازجان')
INSERT INTO dbo.Locations VALUES (7, 122, N' بوشکان')
INSERT INTO dbo.Locations VALUES (7, 122, N' تنگ ارم')
INSERT INTO dbo.Locations VALUES (7, 122, N' دالکی')
INSERT INTO dbo.Locations VALUES (7, 122, N' سعد آباد')
INSERT INTO dbo.Locations VALUES (7, 122, N' شبانکاره')
INSERT INTO dbo.Locations VALUES (7, 122, N' کلمه')
INSERT INTO dbo.Locations VALUES (7, 122, N' وحدتیه')
INSERT INTO dbo.Locations VALUES (7, 123, N' بادوله')
INSERT INTO dbo.Locations VALUES (7, 123, N' خورموج')
INSERT INTO dbo.Locations VALUES (7, 123, N' شنبه')
INSERT INTO dbo.Locations VALUES (7, 123, N' کاکی')
INSERT INTO dbo.Locations VALUES (7, 124, N' آبدان')
INSERT INTO dbo.Locations VALUES (7, 124, N' بردخون')
INSERT INTO dbo.Locations VALUES (7, 124, N' بردستان')
INSERT INTO dbo.Locations VALUES (7, 124, N' بندردیر')
INSERT INTO dbo.Locations VALUES (7, 124, N' دوراهک')
INSERT INTO dbo.Locations VALUES (7, 125, N' امام حسن')
INSERT INTO dbo.Locations VALUES (7, 125, N' بندردیلم')
INSERT INTO dbo.Locations VALUES (7, 126, N' عسلویه')
INSERT INTO dbo.Locations VALUES (7, 126, N' نخل تقی')
INSERT INTO dbo.Locations VALUES (7, 127, N' بندرکنگان')
INSERT INTO dbo.Locations VALUES (7, 127, N' بنک')
INSERT INTO dbo.Locations VALUES (7, 127, N' سیراف')
INSERT INTO dbo.Locations VALUES (7, 128, N' بندرریگ')
INSERT INTO dbo.Locations VALUES (7, 128, N' بندرگناوه')
INSERT INTO dbo.Locations VALUES (8, 129, N' احمد آباد مستوفی')
INSERT INTO dbo.Locations VALUES (8, 129, N' اسلامشهر')
INSERT INTO dbo.Locations VALUES (8, 129, N' چهاردانگه')
INSERT INTO dbo.Locations VALUES (8, 130, N' صالحیه')
INSERT INTO dbo.Locations VALUES (8, 130, N' گلستان')
INSERT INTO dbo.Locations VALUES (8, 130, N' نسیم شهر')
INSERT INTO dbo.Locations VALUES (8, 131, N' پاکدشت')
INSERT INTO dbo.Locations VALUES (8, 131, N' شریف آباد')
INSERT INTO dbo.Locations VALUES (8, 131, N' فرون اباد')
INSERT INTO dbo.Locations VALUES (8, 132, N' بومهن')
INSERT INTO dbo.Locations VALUES (8, 132, N' پردیس')
INSERT INTO dbo.Locations VALUES (8, 133, N' پیشوا')
INSERT INTO dbo.Locations VALUES (8, 134, N' تهران')
INSERT INTO dbo.Locations VALUES (8, 135, N' آبسرد')
INSERT INTO dbo.Locations VALUES (8, 135, N' آبعلی')
INSERT INTO dbo.Locations VALUES (8, 135, N' دماوند')
INSERT INTO dbo.Locations VALUES (8, 135, N' رودهن')
INSERT INTO dbo.Locations VALUES (8, 135, N' کیلان')
INSERT INTO dbo.Locations VALUES (8, 136, N' پرند')
INSERT INTO dbo.Locations VALUES (8, 136, N' رباطکریم')
INSERT INTO dbo.Locations VALUES (8, 136, N' نصیرشهر')
INSERT INTO dbo.Locations VALUES (8, 137, N' باقرشهر')
INSERT INTO dbo.Locations VALUES (8, 137, N' حسن آباد')
INSERT INTO dbo.Locations VALUES (8, 137, N' ری')
INSERT INTO dbo.Locations VALUES (8, 137, N' کهریزک')
INSERT INTO dbo.Locations VALUES (8, 138, N' تجریش')
INSERT INTO dbo.Locations VALUES (8, 138, N' شمشک')
INSERT INTO dbo.Locations VALUES (8, 138, N' فشم')
INSERT INTO dbo.Locations VALUES (8, 138, N' لواسان')
INSERT INTO dbo.Locations VALUES (8, 139, N' اندیشه')
INSERT INTO dbo.Locations VALUES (8, 139, N' باغستان')
INSERT INTO dbo.Locations VALUES (8, 139, N' شاهدشهر')
INSERT INTO dbo.Locations VALUES (8, 139, N' شهریار')
INSERT INTO dbo.Locations VALUES (8, 139, N' صباشهر')
INSERT INTO dbo.Locations VALUES (8, 139, N' فردوسیه')
INSERT INTO dbo.Locations VALUES (8, 139, N' وحیدیه')
INSERT INTO dbo.Locations VALUES (8, 140, N' ارجمند')
INSERT INTO dbo.Locations VALUES (8, 140, N' فیروزکوه')
INSERT INTO dbo.Locations VALUES (8, 141, N' قدس')
INSERT INTO dbo.Locations VALUES (8, 142, N' قرچک')
INSERT INTO dbo.Locations VALUES (8, 143, N' صفادشت')
INSERT INTO dbo.Locations VALUES (8, 143, N' ملارد')
INSERT INTO dbo.Locations VALUES (8, 144, N' جوادآباد')
INSERT INTO dbo.Locations VALUES (8, 144, N' ورامین')
INSERT INTO dbo.Locations VALUES (9, 145, N' اردل')
INSERT INTO dbo.Locations VALUES (9, 145, N' دشتک')
INSERT INTO dbo.Locations VALUES (9, 145, N' سرخون')
INSERT INTO dbo.Locations VALUES (9, 145, N' کاج')
INSERT INTO dbo.Locations VALUES (9, 146, N' بروجن')
INSERT INTO dbo.Locations VALUES (9, 146, N' بلداجی')
INSERT INTO dbo.Locations VALUES (9, 146, N' سفیددشت')
INSERT INTO dbo.Locations VALUES (9, 146, N' فرادبنه')
INSERT INTO dbo.Locations VALUES (9, 146, N' گندمان')
INSERT INTO dbo.Locations VALUES (9, 146, N' نقنه')
INSERT INTO dbo.Locations VALUES (9, 147, N' بن')
INSERT INTO dbo.Locations VALUES (9, 147, N' وردنجان')
INSERT INTO dbo.Locations VALUES (9, 148, N' سامان')
INSERT INTO dbo.Locations VALUES (9, 149, N' سودجان')
INSERT INTO dbo.Locations VALUES (9, 149, N' سورشجان')
INSERT INTO dbo.Locations VALUES (9, 149, N' شهرکرد')
INSERT INTO dbo.Locations VALUES (9, 149, N' طاقانک')
INSERT INTO dbo.Locations VALUES (9, 149, N' فرخ شهر')
INSERT INTO dbo.Locations VALUES (9, 149, N' کیان')
INSERT INTO dbo.Locations VALUES (9, 149, N' نافچ')
INSERT INTO dbo.Locations VALUES (9, 149, N' هارونی')
INSERT INTO dbo.Locations VALUES (9, 149, N' هفشجان')
INSERT INTO dbo.Locations VALUES (9, 150, N' باباحیدر')
INSERT INTO dbo.Locations VALUES (9, 150, N' پردنجان')
INSERT INTO dbo.Locations VALUES (9, 150, N' جونقان')
INSERT INTO dbo.Locations VALUES (9, 150, N' چلیچه')
INSERT INTO dbo.Locations VALUES (9, 150, N' فارسان')
INSERT INTO dbo.Locations VALUES (9, 150, N' گوجان')
INSERT INTO dbo.Locations VALUES (9, 151, N' بازفت')
INSERT INTO dbo.Locations VALUES (9, 151, N' چلگرد')
INSERT INTO dbo.Locations VALUES (9, 151, N' صمصامی')
INSERT INTO dbo.Locations VALUES (9, 152, N' دستنا')
INSERT INTO dbo.Locations VALUES (9, 152, N' شلمزار')
INSERT INTO dbo.Locations VALUES (9, 152, N' گهرو')
INSERT INTO dbo.Locations VALUES (9, 152, N' ناغان')
INSERT INTO dbo.Locations VALUES (9, 153, N' آلونی')
INSERT INTO dbo.Locations VALUES (9, 153, N' سردشت')
INSERT INTO dbo.Locations VALUES (9, 153, N' لردگان')
INSERT INTO dbo.Locations VALUES (9, 153, N' مال خلیفه')
INSERT INTO dbo.Locations VALUES (9, 153, N' منج')
INSERT INTO dbo.Locations VALUES (10, 154, N' ارسک')
INSERT INTO dbo.Locations VALUES (10, 154, N' بشرویه')
INSERT INTO dbo.Locations VALUES (10, 155, N' بیرجند')
INSERT INTO dbo.Locations VALUES (10, 156, N' خوسف')
INSERT INTO dbo.Locations VALUES (10, 156, N' محمدشهر')
INSERT INTO dbo.Locations VALUES (10, 157, N' اسدیه')
INSERT INTO dbo.Locations VALUES (10, 157, N' طبس مسینا')
INSERT INTO dbo.Locations VALUES (10, 157, N' قهستان')
INSERT INTO dbo.Locations VALUES (10, 157, N' گزیک')
INSERT INTO dbo.Locations VALUES (10, 158, N' حاجی آباد')
INSERT INTO dbo.Locations VALUES (10, 158, N' زهان')
INSERT INTO dbo.Locations VALUES (10, 159, N' آیسک')
INSERT INTO dbo.Locations VALUES (10, 159, N' سرایان')
INSERT INTO dbo.Locations VALUES (10, 159, N' سه قلعه')
INSERT INTO dbo.Locations VALUES (10, 160, N' سربیشه')
INSERT INTO dbo.Locations VALUES (10, 160, N' مود')
INSERT INTO dbo.Locations VALUES (10, 161, N' دیهوک')
INSERT INTO dbo.Locations VALUES (10, 161, N' طبس')
INSERT INTO dbo.Locations VALUES (10, 161, N' عشق آباد')
INSERT INTO dbo.Locations VALUES (10, 162, N' اسلامیه')
INSERT INTO dbo.Locations VALUES (10, 162, N' فردوس')
INSERT INTO dbo.Locations VALUES (10, 163, N' آرین شهر')
INSERT INTO dbo.Locations VALUES (10, 163, N' اسفدن')
INSERT INTO dbo.Locations VALUES (10, 163, N' خضری دشت بیاض')
INSERT INTO dbo.Locations VALUES (10, 163, N' قاین')
INSERT INTO dbo.Locations VALUES (10, 163, N' نیمبلوک')
INSERT INTO dbo.Locations VALUES (10, 164, N' شوسف')
INSERT INTO dbo.Locations VALUES (10, 164, N' نهبندان')
INSERT INTO dbo.Locations VALUES (11, 165, N' باخرز')
INSERT INTO dbo.Locations VALUES (11, 166, N' بجستان')
INSERT INTO dbo.Locations VALUES (11, 166, N' یونسی')
INSERT INTO dbo.Locations VALUES (11, 167, N' انابد')
INSERT INTO dbo.Locations VALUES (11, 167, N' بردسکن')
INSERT INTO dbo.Locations VALUES (11, 167, N' شهراباد')
INSERT INTO dbo.Locations VALUES (11, 168, N' شاندیز')
INSERT INTO dbo.Locations VALUES (11, 168, N' طرقبه')
INSERT INTO dbo.Locations VALUES (11, 169, N' تایباد')
INSERT INTO dbo.Locations VALUES (11, 169, N' کاریز')
INSERT INTO dbo.Locations VALUES (11, 169, N' مشهدریزه')
INSERT INTO dbo.Locations VALUES (11, 170, N' احمدابادصولت')
INSERT INTO dbo.Locations VALUES (11, 170, N' تربت جام')
INSERT INTO dbo.Locations VALUES (11, 170, N' صالح آباد')
INSERT INTO dbo.Locations VALUES (11, 170, N' نصرآباد')
INSERT INTO dbo.Locations VALUES (11, 170, N' نیل شهر')
INSERT INTO dbo.Locations VALUES (11, 171, N' بایک')
INSERT INTO dbo.Locations VALUES (11, 171, N' تربت حیدریه')
INSERT INTO dbo.Locations VALUES (11, 171, N' رباط سنگ')
INSERT INTO dbo.Locations VALUES (11, 171, N' کدکن')
INSERT INTO dbo.Locations VALUES (11, 172, N' جغتای')
INSERT INTO dbo.Locations VALUES (11, 173, N' نقاب')
INSERT INTO dbo.Locations VALUES (11, 174, N' چناران')
INSERT INTO dbo.Locations VALUES (11, 174, N' گلبهار')
INSERT INTO dbo.Locations VALUES (11, 174, N' گلمکان')
INSERT INTO dbo.Locations VALUES (11, 175, N' خلیل آباد')
INSERT INTO dbo.Locations VALUES (11, 175, N' کندر')
INSERT INTO dbo.Locations VALUES (11, 176, N' خواف')
INSERT INTO dbo.Locations VALUES (11, 176, N' سلامی')
INSERT INTO dbo.Locations VALUES (11, 176, N' سنگان')
INSERT INTO dbo.Locations VALUES (11, 176, N' قاسم آباد')
INSERT INTO dbo.Locations VALUES (11, 176, N' نشتیفان')
INSERT INTO dbo.Locations VALUES (11, 177, N' سلطان آباد')
INSERT INTO dbo.Locations VALUES (11, 178, N' داورزن')
INSERT INTO dbo.Locations VALUES (11, 179, N' چاپشلو')
INSERT INTO dbo.Locations VALUES (11, 179, N' درگز')
INSERT INTO dbo.Locations VALUES (11, 179, N' لطف آباد')
INSERT INTO dbo.Locations VALUES (11, 179, N' نوخندان')
INSERT INTO dbo.Locations VALUES (11, 180, N' جنگل')
INSERT INTO dbo.Locations VALUES (11, 180, N' رشتخوار')
INSERT INTO dbo.Locations VALUES (11, 181, N' دولت آباد')
INSERT INTO dbo.Locations VALUES (11, 182, N' روداب')
INSERT INTO dbo.Locations VALUES (11, 182, N' سبزوار')
INSERT INTO dbo.Locations VALUES (11, 182, N' ششتمد')
INSERT INTO dbo.Locations VALUES (11, 183, N' سرخس')
INSERT INTO dbo.Locations VALUES (11, 183, N' مزدآوند')
INSERT INTO dbo.Locations VALUES (11, 184, N' سفیدسنگ')
INSERT INTO dbo.Locations VALUES (11, 184, N' فرهادگرد')
INSERT INTO dbo.Locations VALUES (11, 184, N' فریمان')
INSERT INTO dbo.Locations VALUES (11, 184, N' قلندرآباد')
INSERT INTO dbo.Locations VALUES (11, 185, N' فیروزه')
INSERT INTO dbo.Locations VALUES (11, 185, N' همت آباد')
INSERT INTO dbo.Locations VALUES (11, 186, N' باجگیران')
INSERT INTO dbo.Locations VALUES (11, 186, N' قوچان')
INSERT INTO dbo.Locations VALUES (11, 187, N' ریوش')
INSERT INTO dbo.Locations VALUES (11, 187, N' کاشمر')
INSERT INTO dbo.Locations VALUES (11, 188, N' شهرزو')
INSERT INTO dbo.Locations VALUES (11, 188, N' کلات')
INSERT INTO dbo.Locations VALUES (11, 189, N' بیدخت')
INSERT INTO dbo.Locations VALUES (11, 189, N' کاخک')
INSERT INTO dbo.Locations VALUES (11, 189, N' گناباد')
INSERT INTO dbo.Locations VALUES (11, 190, N' رضویه')
INSERT INTO dbo.Locations VALUES (11, 190, N' مشهد')
INSERT INTO dbo.Locations VALUES (11, 190, N' مشهد ثامن')
INSERT INTO dbo.Locations VALUES (11, 190, N' ملک آباد')
INSERT INTO dbo.Locations VALUES (11, 191, N' شادمهر')
INSERT INTO dbo.Locations VALUES (11, 191, N' فیض آباد')
INSERT INTO dbo.Locations VALUES (11, 192, N' بار')
INSERT INTO dbo.Locations VALUES (11, 192, N' چکنه')
INSERT INTO dbo.Locations VALUES (11, 192, N' خرو')
INSERT INTO dbo.Locations VALUES (11, 192, N' درود')
INSERT INTO dbo.Locations VALUES (11, 192, N' عشق آباد')
INSERT INTO dbo.Locations VALUES (11, 192, N' قدمگاه')
INSERT INTO dbo.Locations VALUES (11, 192, N' نیشابور')
INSERT INTO dbo.Locations VALUES (12, 193, N' اسفراین')
INSERT INTO dbo.Locations VALUES (12, 193, N' صفی آباد')
INSERT INTO dbo.Locations VALUES (12, 194, N' بجنورد')
INSERT INTO dbo.Locations VALUES (12, 194, N' چناران شهر')
INSERT INTO dbo.Locations VALUES (12, 194, N' حصارگرمخان')
INSERT INTO dbo.Locations VALUES (12, 195, N' جاجرم')
INSERT INTO dbo.Locations VALUES (12, 195, N' سنخواست')
INSERT INTO dbo.Locations VALUES (12, 195, N' شوقان')
INSERT INTO dbo.Locations VALUES (12, 196, N' راز')
INSERT INTO dbo.Locations VALUES (12, 197, N' زیارت')
INSERT INTO dbo.Locations VALUES (12, 197, N' شیروان')
INSERT INTO dbo.Locations VALUES (12, 197, N' قوشخانه')
INSERT INTO dbo.Locations VALUES (12, 197, N' لوجلی')
INSERT INTO dbo.Locations VALUES (12, 198, N' تیتکانلو')
INSERT INTO dbo.Locations VALUES (12, 198, N' فاروج')
INSERT INTO dbo.Locations VALUES (12, 199, N' ایور')
INSERT INTO dbo.Locations VALUES (12, 199, N' درق')
INSERT INTO dbo.Locations VALUES (12, 199, N' گرمه')
INSERT INTO dbo.Locations VALUES (12, 200, N' آشخانه')
INSERT INTO dbo.Locations VALUES (12, 200, N' آوا')
INSERT INTO dbo.Locations VALUES (12, 200, N' پیش قلعه')
INSERT INTO dbo.Locations VALUES (12, 200, N' قاضی')
INSERT INTO dbo.Locations VALUES (13, 201, N' آبادان')
INSERT INTO dbo.Locations VALUES (13, 201, N' اروندکنار')
INSERT INTO dbo.Locations VALUES (13, 201, N' چویبده')
INSERT INTO dbo.Locations VALUES (13, 202, N' آغاجاری')
INSERT INTO dbo.Locations VALUES (13, 203, N' امیدیه')
INSERT INTO dbo.Locations VALUES (13, 203, N' جایزان')
INSERT INTO dbo.Locations VALUES (13, 204, N' آبژدان')
INSERT INTO dbo.Locations VALUES (13, 204, N' قلعه خواجه')
INSERT INTO dbo.Locations VALUES (13, 205, N' آزادی')
INSERT INTO dbo.Locations VALUES (13, 205, N' اندیمشک')
INSERT INTO dbo.Locations VALUES (13, 205, N' بیدروبه')
INSERT INTO dbo.Locations VALUES (13, 205, N' چم گلک')
INSERT INTO dbo.Locations VALUES (13, 205, N' حسینیه')
INSERT INTO dbo.Locations VALUES (13, 206, N' الهایی')
INSERT INTO dbo.Locations VALUES (13, 206, N' اهواز')
INSERT INTO dbo.Locations VALUES (13, 207, N' ایذه')
INSERT INTO dbo.Locations VALUES (13, 207, N' دهدز')
INSERT INTO dbo.Locations VALUES (13, 208, N' باغ ملک')
INSERT INTO dbo.Locations VALUES (13, 208, N' صیدون')
INSERT INTO dbo.Locations VALUES (13, 208, N' قلعه تل')
INSERT INTO dbo.Locations VALUES (13, 208, N' میداود')
INSERT INTO dbo.Locations VALUES (13, 209, N' شیبان')
INSERT INTO dbo.Locations VALUES (13, 209, N' ملاثانی')
INSERT INTO dbo.Locations VALUES (13, 209, N' ویس')
INSERT INTO dbo.Locations VALUES (13, 210, N' بندرامام خمینی')
INSERT INTO dbo.Locations VALUES (13, 210, N' بندرماهشهر')
INSERT INTO dbo.Locations VALUES (13, 210, N' چمران')
INSERT INTO dbo.Locations VALUES (13, 211, N' بهبهان')
INSERT INTO dbo.Locations VALUES (13, 211, N' تشان')
INSERT INTO dbo.Locations VALUES (13, 211, N' سردشت')
INSERT INTO dbo.Locations VALUES (13, 211, N' منصوریه')
INSERT INTO dbo.Locations VALUES (13, 212, N' حمیدیه')
INSERT INTO dbo.Locations VALUES (13, 213, N' خرمشهر')
INSERT INTO dbo.Locations VALUES (13, 213, N' مقاومت')
INSERT INTO dbo.Locations VALUES (13, 213, N' مینوشهر')
INSERT INTO dbo.Locations VALUES (13, 214, N' چغامیش')
INSERT INTO dbo.Locations VALUES (13, 214, N' حمزه')
INSERT INTO dbo.Locations VALUES (13, 214, N' دزفول')
INSERT INTO dbo.Locations VALUES (13, 214, N' سالند')
INSERT INTO dbo.Locations VALUES (13, 214, N' سیاه منصور')
INSERT INTO dbo.Locations VALUES (13, 214, N' شمس آباد')
INSERT INTO dbo.Locations VALUES (13, 214, N' شهر امام')
INSERT INTO dbo.Locations VALUES (13, 214, N' صفی آباد')
INSERT INTO dbo.Locations VALUES (13, 214, N' میانرود')
INSERT INTO dbo.Locations VALUES (13, 215, N' ابوحمیظه')
INSERT INTO dbo.Locations VALUES (13, 215, N' بستان')
INSERT INTO dbo.Locations VALUES (13, 215, N' سوسنگرد')
INSERT INTO dbo.Locations VALUES (13, 215, N' کوت سیدنعیم')
INSERT INTO dbo.Locations VALUES (13, 216, N' رامشیر')
INSERT INTO dbo.Locations VALUES (13, 216, N' مشراگه')
INSERT INTO dbo.Locations VALUES (13, 217, N' رامهرمز')
INSERT INTO dbo.Locations VALUES (13, 218, N' خنافره')
INSERT INTO dbo.Locations VALUES (13, 218, N' دارخوین')
INSERT INTO dbo.Locations VALUES (13, 218, N' شادگان')
INSERT INTO dbo.Locations VALUES (13, 219, N' الوان')
INSERT INTO dbo.Locations VALUES (13, 219, N' حر')
INSERT INTO dbo.Locations VALUES (13, 219, N' شاوور')
INSERT INTO dbo.Locations VALUES (13, 219, N' شوش')
INSERT INTO dbo.Locations VALUES (13, 219, N' فتح المبین')
INSERT INTO dbo.Locations VALUES (13, 220, N' سرداران')
INSERT INTO dbo.Locations VALUES (13, 220, N' شرافت')
INSERT INTO dbo.Locations VALUES (13, 220, N' شوشتر')
INSERT INTO dbo.Locations VALUES (13, 220, N' گوریه')
INSERT INTO dbo.Locations VALUES (13, 221, N' کوت عبداله')
INSERT INTO dbo.Locations VALUES (13, 222, N' ترکالکی')
INSERT INTO dbo.Locations VALUES (13, 222, N' جنت مکان')
INSERT INTO dbo.Locations VALUES (13, 222, N' سماله')
INSERT INTO dbo.Locations VALUES (13, 222, N' صالح شهر')
INSERT INTO dbo.Locations VALUES (13, 222, N' گتوند')
INSERT INTO dbo.Locations VALUES (13, 223, N' لالی')
INSERT INTO dbo.Locations VALUES (13, 224, N' گلگیر')
INSERT INTO dbo.Locations VALUES (13, 224, N' مسجدسلیمان')
INSERT INTO dbo.Locations VALUES (13, 225, N' هفتگل')
INSERT INTO dbo.Locations VALUES (13, 226, N' زهره')
INSERT INTO dbo.Locations VALUES (13, 226, N' هندیجان')
INSERT INTO dbo.Locations VALUES (13, 227, N' رفیع')
INSERT INTO dbo.Locations VALUES (13, 227, N' هویزه')
INSERT INTO dbo.Locations VALUES (14, 228, N' ابهر')
INSERT INTO dbo.Locations VALUES (14, 228, N' صایین قلعه')
INSERT INTO dbo.Locations VALUES (14, 228, N' هیدج')
INSERT INTO dbo.Locations VALUES (14, 229, N' حلب')
INSERT INTO dbo.Locations VALUES (14, 229, N' زرین آباد')
INSERT INTO dbo.Locations VALUES (14, 230, N' زرین رود')
INSERT INTO dbo.Locations VALUES (14, 230, N' سجاس')
INSERT INTO dbo.Locations VALUES (14, 230, N' سهرورد')
INSERT INTO dbo.Locations VALUES (14, 230, N' قیدار')
INSERT INTO dbo.Locations VALUES (14, 230, N' کرسف')
INSERT INTO dbo.Locations VALUES (14, 230, N' گرماب')
INSERT INTO dbo.Locations VALUES (14, 230, N' نوربهار')
INSERT INTO dbo.Locations VALUES (14, 231, N' خرمدره')
INSERT INTO dbo.Locations VALUES (14, 232, N' ارمغانخانه')
INSERT INTO dbo.Locations VALUES (14, 232, N' زنجان')
INSERT INTO dbo.Locations VALUES (14, 232, N' نیک پی')
INSERT INTO dbo.Locations VALUES (14, 233, N' سلطانیه')
INSERT INTO dbo.Locations VALUES (14, 234, N' آب بر')
INSERT INTO dbo.Locations VALUES (14, 234, N' چورزق')
INSERT INTO dbo.Locations VALUES (14, 235, N' دندی')
INSERT INTO dbo.Locations VALUES (14, 235, N' ماه نشان')
INSERT INTO dbo.Locations VALUES (15, 236, N' آرادان')
INSERT INTO dbo.Locations VALUES (15, 236, N' کهن آباد')
INSERT INTO dbo.Locations VALUES (15, 237, N' امیریه')
INSERT INTO dbo.Locations VALUES (15, 237, N' دامغان')
INSERT INTO dbo.Locations VALUES (15, 237, N' دیباج')
INSERT INTO dbo.Locations VALUES (15, 237, N' کلاته')
INSERT INTO dbo.Locations VALUES (15, 238, N' سرخه')
INSERT INTO dbo.Locations VALUES (15, 239, N' سمنان')
INSERT INTO dbo.Locations VALUES (15, 240, N' بسطام')
INSERT INTO dbo.Locations VALUES (15, 240, N' بیارجمند')
INSERT INTO dbo.Locations VALUES (15, 240, N' رودیان')
INSERT INTO dbo.Locations VALUES (15, 240, N' شاهرود')
INSERT INTO dbo.Locations VALUES (15, 240, N' کلاته خیج')
INSERT INTO dbo.Locations VALUES (15, 240, N' مجن')
INSERT INTO dbo.Locations VALUES (15, 241, N' ایوانکی')
INSERT INTO dbo.Locations VALUES (15, 241, N' گرمسار')
INSERT INTO dbo.Locations VALUES (15, 242, N' درجزین')
INSERT INTO dbo.Locations VALUES (15, 242, N' شهمیرزاد')
INSERT INTO dbo.Locations VALUES (15, 242, N' مهدی شهر')
INSERT INTO dbo.Locations VALUES (15, 243, N' میامی')
INSERT INTO dbo.Locations VALUES (16, 244, N' ایرانشهر')
INSERT INTO dbo.Locations VALUES (16, 244, N' بزمان')
INSERT INTO dbo.Locations VALUES (16, 244, N' بمپور')
INSERT INTO dbo.Locations VALUES (16, 244, N' محمدان')
INSERT INTO dbo.Locations VALUES (16, 245, N' چابهار')
INSERT INTO dbo.Locations VALUES (16, 245, N' نگور')
INSERT INTO dbo.Locations VALUES (16, 246, N' خاش')
INSERT INTO dbo.Locations VALUES (16, 246, N' نوک آباد')
INSERT INTO dbo.Locations VALUES (16, 247, N' گلمورتی')
INSERT INTO dbo.Locations VALUES (16, 248, N' بنجار')
INSERT INTO dbo.Locations VALUES (16, 248, N' زابل')
INSERT INTO dbo.Locations VALUES (16, 249, N' زاهدان')
INSERT INTO dbo.Locations VALUES (16, 249, N' نصرت آباد')
INSERT INTO dbo.Locations VALUES (16, 250, N' زهک')
INSERT INTO dbo.Locations VALUES (16, 251, N' جالق')
INSERT INTO dbo.Locations VALUES (16, 251, N' سراوان')
INSERT INTO dbo.Locations VALUES (16, 251, N' سیرکان')
INSERT INTO dbo.Locations VALUES (16, 251, N' گشت')
INSERT INTO dbo.Locations VALUES (16, 251, N' محمدی')
INSERT INTO dbo.Locations VALUES (16, 252, N' پیشین')
INSERT INTO dbo.Locations VALUES (16, 252, N' راسک')
INSERT INTO dbo.Locations VALUES (16, 252, N' سرباز')
INSERT INTO dbo.Locations VALUES (16, 253, N' سوران')
INSERT INTO dbo.Locations VALUES (16, 253, N' هیدوچ')
INSERT INTO dbo.Locations VALUES (16, 254, N' فنوج')
INSERT INTO dbo.Locations VALUES (16, 255, N' قصرقند')
INSERT INTO dbo.Locations VALUES (16, 256, N' زرآباد')
INSERT INTO dbo.Locations VALUES (16, 256, N' کنارک')
INSERT INTO dbo.Locations VALUES (16, 257, N' مهرستان')
INSERT INTO dbo.Locations VALUES (16, 258, N' میرجاوه')
INSERT INTO dbo.Locations VALUES (16, 259, N' اسپکه')
INSERT INTO dbo.Locations VALUES (16, 259, N' بنت')
INSERT INTO dbo.Locations VALUES (16, 259, N' نیک شهر')
INSERT INTO dbo.Locations VALUES (16, 260, N' ادیمی')
INSERT INTO dbo.Locations VALUES (16, 261, N' شهرک علی اکبر')
INSERT INTO dbo.Locations VALUES (16, 261, N' محمدآباد')
INSERT INTO dbo.Locations VALUES (16, 262, N' دوست محمد')
INSERT INTO dbo.Locations VALUES (17, 263, N' آباده')
INSERT INTO dbo.Locations VALUES (17, 263, N' ایزدخواست')
INSERT INTO dbo.Locations VALUES (17, 263, N' بهمن')
INSERT INTO dbo.Locations VALUES (17, 263, N' سورمق')
INSERT INTO dbo.Locations VALUES (17, 263, N' صغاد')
INSERT INTO dbo.Locations VALUES (17, 264, N' ارسنجان')
INSERT INTO dbo.Locations VALUES (17, 265, N' استهبان')
INSERT INTO dbo.Locations VALUES (17, 265, N' ایج')
INSERT INTO dbo.Locations VALUES (17, 265, N' رونیز')
INSERT INTO dbo.Locations VALUES (17, 266, N' اقلید')
INSERT INTO dbo.Locations VALUES (17, 266, N' حسن اباد')
INSERT INTO dbo.Locations VALUES (17, 266, N' دژکرد')
INSERT INTO dbo.Locations VALUES (17, 266, N' سده')
INSERT INTO dbo.Locations VALUES (17, 267, N' بوانات')
INSERT INTO dbo.Locations VALUES (17, 267, N' حسامی')
INSERT INTO dbo.Locations VALUES (17, 267, N' کره ای')
INSERT INTO dbo.Locations VALUES (17, 267, N' مزایجان')
INSERT INTO dbo.Locations VALUES (17, 268, N' سعادت شهر')
INSERT INTO dbo.Locations VALUES (17, 268, N' مادرسلیمان')
INSERT INTO dbo.Locations VALUES (17, 269, N' باب انار')
INSERT INTO dbo.Locations VALUES (17, 269, N' جهرم')
INSERT INTO dbo.Locations VALUES (17, 269, N' خاوران')
INSERT INTO dbo.Locations VALUES (17, 269, N' دوزه')
INSERT INTO dbo.Locations VALUES (17, 269, N' قطب آباد')
INSERT INTO dbo.Locations VALUES (17, 270, N' خرامه')
INSERT INTO dbo.Locations VALUES (17, 270, N' سلطان شهر')
INSERT INTO dbo.Locations VALUES (17, 271, N' صفاشهر')
INSERT INTO dbo.Locations VALUES (17, 271, N' قادراباد')
INSERT INTO dbo.Locations VALUES (17, 272, N' خنج')
INSERT INTO dbo.Locations VALUES (17, 273, N' جنت شهر')
INSERT INTO dbo.Locations VALUES (17, 273, N' داراب')
INSERT INTO dbo.Locations VALUES (17, 273, N' دوبرجی')
INSERT INTO dbo.Locations VALUES (17, 273, N' فدامی')
INSERT INTO dbo.Locations VALUES (17, 274, N' کوپن')
INSERT INTO dbo.Locations VALUES (17, 274, N' مصیری')
INSERT INTO dbo.Locations VALUES (17, 275, N' حاجی آباد')
INSERT INTO dbo.Locations VALUES (17, 275, N' دبیران')
INSERT INTO dbo.Locations VALUES (17, 275, N' شهرپیر')
INSERT INTO dbo.Locations VALUES (17, 276, N' اردکان')
INSERT INTO dbo.Locations VALUES (17, 276, N' بیضا')
INSERT INTO dbo.Locations VALUES (17, 276, N' هماشهر')
INSERT INTO dbo.Locations VALUES (17, 277, N' سروستان')
INSERT INTO dbo.Locations VALUES (17, 277, N' کوهنجان')
INSERT INTO dbo.Locations VALUES (17, 278, N' خانه زنیان')
INSERT INTO dbo.Locations VALUES (17, 278, N' داریان')
INSERT INTO dbo.Locations VALUES (17, 278, N' زرقان')
INSERT INTO dbo.Locations VALUES (17, 278, N' شهرصدرا')
INSERT INTO dbo.Locations VALUES (17, 278, N' شیراز')
INSERT INTO dbo.Locations VALUES (17, 278, N' لپویی')
INSERT INTO dbo.Locations VALUES (17, 279, N' دهرم')
INSERT INTO dbo.Locations VALUES (17, 279, N' فراشبند')
INSERT INTO dbo.Locations VALUES (17, 279, N' نوجین')
INSERT INTO dbo.Locations VALUES (17, 280, N' زاهدشهر')
INSERT INTO dbo.Locations VALUES (17, 280, N' ششده')
INSERT INTO dbo.Locations VALUES (17, 280, N' فسا')
INSERT INTO dbo.Locations VALUES (17, 280, N' قره بلاغ')
INSERT INTO dbo.Locations VALUES (17, 280, N' میانشهر')
INSERT INTO dbo.Locations VALUES (17, 280, N' نوبندگان')
INSERT INTO dbo.Locations VALUES (17, 281, N' فیروزآباد')
INSERT INTO dbo.Locations VALUES (17, 281, N' میمند')
INSERT INTO dbo.Locations VALUES (17, 282, N' افزر')
INSERT INTO dbo.Locations VALUES (17, 282, N' امام شهر')
INSERT INTO dbo.Locations VALUES (17, 282, N' قیر')
INSERT INTO dbo.Locations VALUES (17, 282, N' کارزین فتح آباد)')
INSERT INTO dbo.Locations VALUES (17, 282, N' مبارک آباددیز')
INSERT INTO dbo.Locations VALUES (17, 283, N' بالاده')
INSERT INTO dbo.Locations VALUES (17, 283, N' خشت')
INSERT INTO dbo.Locations VALUES (17, 283, N' قایمیه')
INSERT INTO dbo.Locations VALUES (17, 283, N' کازرون')
INSERT INTO dbo.Locations VALUES (17, 283, N' کنارتخته')
INSERT INTO dbo.Locations VALUES (17, 283, N' نودان')
INSERT INTO dbo.Locations VALUES (17, 284, N' کوار')
INSERT INTO dbo.Locations VALUES (17, 285, N' گراش')
INSERT INTO dbo.Locations VALUES (17, 286, N' اوز')
INSERT INTO dbo.Locations VALUES (17, 286, N' بنارویه')
INSERT INTO dbo.Locations VALUES (17, 286, N' بیرم')
INSERT INTO dbo.Locations VALUES (17, 286, N' جویم')
INSERT INTO dbo.Locations VALUES (17, 286, N' خور')
INSERT INTO dbo.Locations VALUES (17, 286, N' عمادده')
INSERT INTO dbo.Locations VALUES (17, 286, N' لار')
INSERT INTO dbo.Locations VALUES (17, 286, N' لطیفی')
INSERT INTO dbo.Locations VALUES (17, 287, N' اشکنان')
INSERT INTO dbo.Locations VALUES (17, 287, N' اهل')
INSERT INTO dbo.Locations VALUES (17, 287, N' علامرودشت')
INSERT INTO dbo.Locations VALUES (17, 287, N' لامرد')
INSERT INTO dbo.Locations VALUES (17, 288, N' خانیمن')
INSERT INTO dbo.Locations VALUES (17, 288, N' رامجرد')
INSERT INTO dbo.Locations VALUES (17, 288, N' سیدان')
INSERT INTO dbo.Locations VALUES (17, 288, N' کامفیروز')
INSERT INTO dbo.Locations VALUES (17, 288, N' مرودشت')
INSERT INTO dbo.Locations VALUES (17, 289, N' بابامنیر')
INSERT INTO dbo.Locations VALUES (17, 289, N' خومه زار')
INSERT INTO dbo.Locations VALUES (17, 289, N' نورآباد')
INSERT INTO dbo.Locations VALUES (17, 290, N' اسیر')
INSERT INTO dbo.Locations VALUES (17, 290, N' خوزی')
INSERT INTO dbo.Locations VALUES (17, 290, N' گله دار')
INSERT INTO dbo.Locations VALUES (17, 290, N' مهر')
INSERT INTO dbo.Locations VALUES (17, 290, N' وراوی')
INSERT INTO dbo.Locations VALUES (17, 291, N' آباده طشک')
INSERT INTO dbo.Locations VALUES (17, 291, N' قطرویه')
INSERT INTO dbo.Locations VALUES (17, 291, N' مشکان')
INSERT INTO dbo.Locations VALUES (17, 291, N' نی ریز')
INSERT INTO dbo.Locations VALUES (18, 292, N' آبیک')
INSERT INTO dbo.Locations VALUES (18, 292, N' خاکعلی')
INSERT INTO dbo.Locations VALUES (18, 293, N' آبگرم')
INSERT INTO dbo.Locations VALUES (18, 293, N' آوج')
INSERT INTO dbo.Locations VALUES (18, 294, N' الوند')
INSERT INTO dbo.Locations VALUES (18, 294, N' بیدستان')
INSERT INTO dbo.Locations VALUES (18, 294, N' شریفیه')
INSERT INTO dbo.Locations VALUES (18, 294, N' محمدیه')
INSERT INTO dbo.Locations VALUES (18, 295, N' ارداق')
INSERT INTO dbo.Locations VALUES (18, 295, N' بویین زهرا')
INSERT INTO dbo.Locations VALUES (18, 295, N' دانسفهان')
INSERT INTO dbo.Locations VALUES (18, 295, N' سگزآباد')
INSERT INTO dbo.Locations VALUES (18, 295, N' شال')
INSERT INTO dbo.Locations VALUES (18, 296, N' اسفرورین')
INSERT INTO dbo.Locations VALUES (18, 296, N' تاکستان')
INSERT INTO dbo.Locations VALUES (18, 296, N' خرمدشت')
INSERT INTO dbo.Locations VALUES (18, 296, N' ضیاڈآباد')
INSERT INTO dbo.Locations VALUES (18, 296, N' نرجه')
INSERT INTO dbo.Locations VALUES (18, 297, N' اقبالیه')
INSERT INTO dbo.Locations VALUES (18, 297, N' رازمیان')
INSERT INTO dbo.Locations VALUES (18, 297, N' سیردان')
INSERT INTO dbo.Locations VALUES (18, 297, N' قزوین')
INSERT INTO dbo.Locations VALUES (18, 297, N' کوهین')
INSERT INTO dbo.Locations VALUES (18, 297, N' محمودآبادنمونه')
INSERT INTO dbo.Locations VALUES (18, 297, N' معلم کلایه')
INSERT INTO dbo.Locations VALUES (19, 298, N' جعفریه')
INSERT INTO dbo.Locations VALUES (19, 298, N' دستجرد')
INSERT INTO dbo.Locations VALUES (19, 298, N' سلفچگان')
INSERT INTO dbo.Locations VALUES (19, 298, N' قم')
INSERT INTO dbo.Locations VALUES (19, 298, N' قنوات')
INSERT INTO dbo.Locations VALUES (19, 298, N' کهک')
INSERT INTO dbo.Locations VALUES (20, 299, N' آرمرده')
INSERT INTO dbo.Locations VALUES (20, 299, N' بانه')
INSERT INTO dbo.Locations VALUES (20, 299, N' بویین سفلی')
INSERT INTO dbo.Locations VALUES (20, 299, N' کانی سور')
INSERT INTO dbo.Locations VALUES (20, 300, N' بابارشانی')
INSERT INTO dbo.Locations VALUES (20, 300, N' بیجار')
INSERT INTO dbo.Locations VALUES (20, 300, N' پیرتاج')
INSERT INTO dbo.Locations VALUES (20, 300, N' توپ آغاج')
INSERT INTO dbo.Locations VALUES (20, 300, N' یاسوکند')
INSERT INTO dbo.Locations VALUES (20, 301, N' بلبان آباد')
INSERT INTO dbo.Locations VALUES (20, 301, N' دهگلان')
INSERT INTO dbo.Locations VALUES (20, 302, N' دیواندره')
INSERT INTO dbo.Locations VALUES (20, 302, N' زرینه')
INSERT INTO dbo.Locations VALUES (20, 303, N' اورامان تخت')
INSERT INTO dbo.Locations VALUES (20, 303, N' سروآباد')
INSERT INTO dbo.Locations VALUES (20, 304, N' سقز')
INSERT INTO dbo.Locations VALUES (20, 304, N' صاحب')
INSERT INTO dbo.Locations VALUES (20, 305, N' سنندج')
INSERT INTO dbo.Locations VALUES (20, 305, N' شویشه')
INSERT INTO dbo.Locations VALUES (20, 306, N' دزج')
INSERT INTO dbo.Locations VALUES (20, 306, N' دلبران')
INSERT INTO dbo.Locations VALUES (20, 306, N' سریش آباد')
INSERT INTO dbo.Locations VALUES (20, 306, N' قروه')
INSERT INTO dbo.Locations VALUES (20, 307, N' کامیاران')
INSERT INTO dbo.Locations VALUES (20, 307, N' موچش')
INSERT INTO dbo.Locations VALUES (20, 308, N' برده رشه')
INSERT INTO dbo.Locations VALUES (20, 308, N' چناره')
INSERT INTO dbo.Locations VALUES (20, 308, N' کانی دینار')
INSERT INTO dbo.Locations VALUES (20, 308, N' مریوان')
INSERT INTO dbo.Locations VALUES (21, 309, N' ارزوییه')
INSERT INTO dbo.Locations VALUES (21, 310, N' امین شهر')
INSERT INTO dbo.Locations VALUES (21, 310, N' انار')
INSERT INTO dbo.Locations VALUES (21, 311, N' بافت')
INSERT INTO dbo.Locations VALUES (21, 311, N' بزنجان')
INSERT INTO dbo.Locations VALUES (21, 312, N' بردسیر')
INSERT INTO dbo.Locations VALUES (21, 312, N' دشتکار')
INSERT INTO dbo.Locations VALUES (21, 312, N' گلزار')
INSERT INTO dbo.Locations VALUES (21, 312, N' لاله زار')
INSERT INTO dbo.Locations VALUES (21, 312, N' نگار')
INSERT INTO dbo.Locations VALUES (21, 313, N' بروات')
INSERT INTO dbo.Locations VALUES (21, 313, N' بم')
INSERT INTO dbo.Locations VALUES (21, 314, N' بلوک')
INSERT INTO dbo.Locations VALUES (21, 314, N' جبالبارز')
INSERT INTO dbo.Locations VALUES (21, 314, N' جیرفت')
INSERT INTO dbo.Locations VALUES (21, 314, N' درب بهشت')
INSERT INTO dbo.Locations VALUES (21, 315, N' رابر')
INSERT INTO dbo.Locations VALUES (21, 315, N' هنزا')
INSERT INTO dbo.Locations VALUES (21, 316, N' راور')
INSERT INTO dbo.Locations VALUES (21, 316, N' هجدک')
INSERT INTO dbo.Locations VALUES (21, 317, N' بهرمان')
INSERT INTO dbo.Locations VALUES (21, 317, N' رفسنجان')
INSERT INTO dbo.Locations VALUES (21, 317, N' صفاییه')
INSERT INTO dbo.Locations VALUES (21, 317, N' کشکوییه')
INSERT INTO dbo.Locations VALUES (21, 317, N' مس سرچشمه')
INSERT INTO dbo.Locations VALUES (21, 318, N' رودبار')
INSERT INTO dbo.Locations VALUES (21, 318, N' زهکلوت')
INSERT INTO dbo.Locations VALUES (21, 319, N' گنبکی')
INSERT INTO dbo.Locations VALUES (21, 319, N' محمدآباد')
INSERT INTO dbo.Locations VALUES (21, 320, N' خانوک')
INSERT INTO dbo.Locations VALUES (21, 320, N' ریحان')
INSERT INTO dbo.Locations VALUES (21, 320, N' زرند')
INSERT INTO dbo.Locations VALUES (21, 320, N' یزدان شهر')
INSERT INTO dbo.Locations VALUES (21, 321, N' بلورد')
INSERT INTO dbo.Locations VALUES (21, 321, N' پاریز')
INSERT INTO dbo.Locations VALUES (21, 321, N' خواجو شهر')
INSERT INTO dbo.Locations VALUES (21, 321, N' زیدآباد')
INSERT INTO dbo.Locations VALUES (21, 321, N' سیرجان')
INSERT INTO dbo.Locations VALUES (21, 321, N' نجف شهر')
INSERT INTO dbo.Locations VALUES (21, 321, N' هماشهر')
INSERT INTO dbo.Locations VALUES (21, 322, N' جوزم')
INSERT INTO dbo.Locations VALUES (21, 322, N' خاتون اباد')
INSERT INTO dbo.Locations VALUES (21, 322, N' خورسند')
INSERT INTO dbo.Locations VALUES (21, 322, N' دهج')
INSERT INTO dbo.Locations VALUES (21, 322, N' شهربابک')
INSERT INTO dbo.Locations VALUES (21, 323, N' دوساری')
INSERT INTO dbo.Locations VALUES (21, 323, N' عنبرآباد')
INSERT INTO dbo.Locations VALUES (21, 323, N' مردهک')
INSERT INTO dbo.Locations VALUES (21, 324, N' فاریاب')
INSERT INTO dbo.Locations VALUES (21, 325, N' فهرج')
INSERT INTO dbo.Locations VALUES (21, 326, N' قلعه گنج')
INSERT INTO dbo.Locations VALUES (21, 327, N' اختیارآباد')
INSERT INTO dbo.Locations VALUES (21, 327, N' اندوهجرد')
INSERT INTO dbo.Locations VALUES (21, 327, N' باغین')
INSERT INTO dbo.Locations VALUES (21, 327, N' جوپار')
INSERT INTO dbo.Locations VALUES (21, 327, N' چترود')
INSERT INTO dbo.Locations VALUES (21, 327, N' راین')
INSERT INTO dbo.Locations VALUES (21, 327, N' زنگی آباد')
INSERT INTO dbo.Locations VALUES (21, 327, N' شهداد')
INSERT INTO dbo.Locations VALUES (21, 327, N' کاظم آباد')
INSERT INTO dbo.Locations VALUES (21, 327, N' کرمان')
INSERT INTO dbo.Locations VALUES (21, 327, N' گلباف')
INSERT INTO dbo.Locations VALUES (21, 327, N' ماهان')
INSERT INTO dbo.Locations VALUES (21, 327, N' محی آباد')
INSERT INTO dbo.Locations VALUES (21, 328, N' کوهبنان')
INSERT INTO dbo.Locations VALUES (21, 328, N' کیانشهر')
INSERT INTO dbo.Locations VALUES (21, 329, N' کهنوج')
INSERT INTO dbo.Locations VALUES (21, 330, N' منوجان')
INSERT INTO dbo.Locations VALUES (21, 330, N' نودژ')
INSERT INTO dbo.Locations VALUES (21, 331, N' نرماشیر')
INSERT INTO dbo.Locations VALUES (21, 331, N' نظام شهر')
INSERT INTO dbo.Locations VALUES (22, 332, N' اسلام آبادغرب')
INSERT INTO dbo.Locations VALUES (22, 332, N' حمیل')
INSERT INTO dbo.Locations VALUES (22, 333, N' بانوره')
INSERT INTO dbo.Locations VALUES (22, 333, N' باینگان')
INSERT INTO dbo.Locations VALUES (22, 333, N' پاوه')
INSERT INTO dbo.Locations VALUES (22, 333, N' نودشه')
INSERT INTO dbo.Locations VALUES (22, 333, N' نوسود')
INSERT INTO dbo.Locations VALUES (22, 334, N' ازگله')
INSERT INTO dbo.Locations VALUES (22, 334, N' تازه آباد')
INSERT INTO dbo.Locations VALUES (22, 335, N' جوانرود')
INSERT INTO dbo.Locations VALUES (22, 336, N' ریجاب')
INSERT INTO dbo.Locations VALUES (22, 336, N' کرند')
INSERT INTO dbo.Locations VALUES (22, 336, N' گهواره')
INSERT INTO dbo.Locations VALUES (22, 337, N' روانسر')
INSERT INTO dbo.Locations VALUES (22, 337, N' شاهو')
INSERT INTO dbo.Locations VALUES (22, 338, N' سرپل ذهاب')
INSERT INTO dbo.Locations VALUES (22, 339, N' سطر')
INSERT INTO dbo.Locations VALUES (22, 339, N' سنقر')
INSERT INTO dbo.Locations VALUES (22, 340, N' صحنه')
INSERT INTO dbo.Locations VALUES (22, 340, N' میان راهان')
INSERT INTO dbo.Locations VALUES (22, 341, N' سومار')
INSERT INTO dbo.Locations VALUES (22, 341, N' قصرشیرین')
INSERT INTO dbo.Locations VALUES (22, 342, N' رباط')
INSERT INTO dbo.Locations VALUES (22, 342, N' کرمانشاه')
INSERT INTO dbo.Locations VALUES (22, 342, N' کوزران')
INSERT INTO dbo.Locations VALUES (22, 342, N' هلشی')
INSERT INTO dbo.Locations VALUES (22, 343, N' کنگاور')
INSERT INTO dbo.Locations VALUES (22, 343, N' گودین')
INSERT INTO dbo.Locations VALUES (22, 344, N' سرمست')
INSERT INTO dbo.Locations VALUES (22, 344, N' گیلانغرب')
INSERT INTO dbo.Locations VALUES (22, 345, N' بیستون')
INSERT INTO dbo.Locations VALUES (22, 345, N' هرسین')
INSERT INTO dbo.Locations VALUES (23, 346, N' باشت')
INSERT INTO dbo.Locations VALUES (23, 347, N' چیتاب')
INSERT INTO dbo.Locations VALUES (23, 347, N' گراب سفلی')
INSERT INTO dbo.Locations VALUES (23, 347, N' مادوان')
INSERT INTO dbo.Locations VALUES (23, 347, N' مارگون')
INSERT INTO dbo.Locations VALUES (23, 347, N' یاسوج')
INSERT INTO dbo.Locations VALUES (23, 348, N' لیکک')
INSERT INTO dbo.Locations VALUES (23, 349, N' چرام')
INSERT INTO dbo.Locations VALUES (23, 349, N' سرفاریاب')
INSERT INTO dbo.Locations VALUES (23, 350, N' پاتاوه')
INSERT INTO dbo.Locations VALUES (23, 350, N' سی سخت')
INSERT INTO dbo.Locations VALUES (23, 351, N' دهدشت')
INSERT INTO dbo.Locations VALUES (23, 351, N' دیشموک')
INSERT INTO dbo.Locations VALUES (23, 351, N' سوق')
INSERT INTO dbo.Locations VALUES (23, 351, N' قلعه رییسی')
INSERT INTO dbo.Locations VALUES (23, 352, N' دوگنبدان')
INSERT INTO dbo.Locations VALUES (23, 353, N' لنده')
INSERT INTO dbo.Locations VALUES (24, 354, N' آزادشهر')
INSERT INTO dbo.Locations VALUES (24, 354, N' نگین شهر')
INSERT INTO dbo.Locations VALUES (24, 354, N' نوده خاندوز')
INSERT INTO dbo.Locations VALUES (24, 355, N' آق قلا')
INSERT INTO dbo.Locations VALUES (24, 355, N' انبارآلوم')
INSERT INTO dbo.Locations VALUES (24, 356, N' بندرگز')
INSERT INTO dbo.Locations VALUES (24, 356, N' نوکنده')
INSERT INTO dbo.Locations VALUES (24, 357, N' بندرترکمن')
INSERT INTO dbo.Locations VALUES (24, 358, N' تاتارعلیا')
INSERT INTO dbo.Locations VALUES (24, 358, N' خان ببین')
INSERT INTO dbo.Locations VALUES (24, 358, N' دلند')
INSERT INTO dbo.Locations VALUES (24, 358, N' رامیان')
INSERT INTO dbo.Locations VALUES (24, 359, N' سنگدوین')
INSERT INTO dbo.Locations VALUES (24, 359, N' علی اباد')
INSERT INTO dbo.Locations VALUES (24, 359, N' فاضل آباد')
INSERT INTO dbo.Locations VALUES (24, 359, N' مزرعه')
INSERT INTO dbo.Locations VALUES (24, 360, N' کردکوی')
INSERT INTO dbo.Locations VALUES (24, 361, N' فراغی')
INSERT INTO dbo.Locations VALUES (24, 361, N' کلاله')
INSERT INTO dbo.Locations VALUES (24, 362, N' گالیکش')
INSERT INTO dbo.Locations VALUES (24, 363, N' جلین')
INSERT INTO dbo.Locations VALUES (24, 363, N' سرخنکلاته')
INSERT INTO dbo.Locations VALUES (24, 363, N' گرگان')
INSERT INTO dbo.Locations VALUES (24, 364, N' سیمین شهر')
INSERT INTO dbo.Locations VALUES (24, 364, N' گمیش تپه')
INSERT INTO dbo.Locations VALUES (24, 365, N' اینچه برون')
INSERT INTO dbo.Locations VALUES (24, 365, N' گنبدکاووس')
INSERT INTO dbo.Locations VALUES (24, 366, N' مراوه')
INSERT INTO dbo.Locations VALUES (24, 367, N' مینودشت')
INSERT INTO dbo.Locations VALUES (25, 368, N' آستارا')
INSERT INTO dbo.Locations VALUES (25, 368, N' لوندویل')
INSERT INTO dbo.Locations VALUES (25, 369, N' آستانه اشرفیه')
INSERT INTO dbo.Locations VALUES (25, 369, N' کیاشهر')
INSERT INTO dbo.Locations VALUES (25, 370, N' املش')
INSERT INTO dbo.Locations VALUES (25, 370, N' رانکوه')
INSERT INTO dbo.Locations VALUES (25, 371, N' بندرانزلی')
INSERT INTO dbo.Locations VALUES (25, 372, N' خشکبیجار')
INSERT INTO dbo.Locations VALUES (25, 372, N' خمام')
INSERT INTO dbo.Locations VALUES (25, 372, N' رشت')
INSERT INTO dbo.Locations VALUES (25, 372, N' سنگر')
INSERT INTO dbo.Locations VALUES (25, 372, N' کوچصفهان')
INSERT INTO dbo.Locations VALUES (25, 372, N' لشت نشاء')
INSERT INTO dbo.Locations VALUES (25, 372, N' لولمان')
INSERT INTO dbo.Locations VALUES (25, 373, N' پره سر')
INSERT INTO dbo.Locations VALUES (25, 373, N' رضوانشهر')
INSERT INTO dbo.Locations VALUES (25, 374, N' بره سر')
INSERT INTO dbo.Locations VALUES (25, 374, N' توتکابن')
INSERT INTO dbo.Locations VALUES (25, 374, N' جیرنده')
INSERT INTO dbo.Locations VALUES (25, 374, N' رستم آباد')
INSERT INTO dbo.Locations VALUES (25, 374, N' رودبار')
INSERT INTO dbo.Locations VALUES (25, 374, N' لوشان')
INSERT INTO dbo.Locations VALUES (25, 374, N' منجیل')
INSERT INTO dbo.Locations VALUES (25, 375, N' چابکسر')
INSERT INTO dbo.Locations VALUES (25, 375, N' رحیم آباد')
INSERT INTO dbo.Locations VALUES (25, 375, N' رودسر')
INSERT INTO dbo.Locations VALUES (25, 375, N' کلاچای')
INSERT INTO dbo.Locations VALUES (25, 375, N' واجارگاه')
INSERT INTO dbo.Locations VALUES (25, 376, N' دیلمان')
INSERT INTO dbo.Locations VALUES (25, 376, N' سیاهکل')
INSERT INTO dbo.Locations VALUES (25, 377, N' احمدسرگوراب')
INSERT INTO dbo.Locations VALUES (25, 377, N' شفت')
INSERT INTO dbo.Locations VALUES (25, 378, N' صومعه سرا')
INSERT INTO dbo.Locations VALUES (25, 378, N' گوراب زرمیخ')
INSERT INTO dbo.Locations VALUES (25, 378, N' مرجقل')
INSERT INTO dbo.Locations VALUES (25, 379, N' اسالم')
INSERT INTO dbo.Locations VALUES (25, 379, N' چوبر')
INSERT INTO dbo.Locations VALUES (25, 379, N' حویق')
INSERT INTO dbo.Locations VALUES (25, 379, N' لیسار')
INSERT INTO dbo.Locations VALUES (25, 379, N' هشتپر تالش)')
INSERT INTO dbo.Locations VALUES (25, 380, N' فومن')
INSERT INTO dbo.Locations VALUES (25, 380, N' ماسوله')
INSERT INTO dbo.Locations VALUES (25, 380, N' ماکلوان')
INSERT INTO dbo.Locations VALUES (25, 381, N' رودبنه')
INSERT INTO dbo.Locations VALUES (25, 381, N' لاهیجان')
INSERT INTO dbo.Locations VALUES (25, 382, N' اطاقور')
INSERT INTO dbo.Locations VALUES (25, 382, N' چاف و چمخاله')
INSERT INTO dbo.Locations VALUES (25, 382, N' شلمان')
INSERT INTO dbo.Locations VALUES (25, 382, N' کومله')
INSERT INTO dbo.Locations VALUES (25, 382, N' لنگرود')
INSERT INTO dbo.Locations VALUES (25, 383, N' بازار جمعه')
INSERT INTO dbo.Locations VALUES (25, 383, N' ماسال')
INSERT INTO dbo.Locations VALUES (26, 384, N' ازنا')
INSERT INTO dbo.Locations VALUES (26, 384, N' مومن آباد')
INSERT INTO dbo.Locations VALUES (26, 385, N' الیگودرز')
INSERT INTO dbo.Locations VALUES (26, 385, N' شول آباد')
INSERT INTO dbo.Locations VALUES (26, 386, N' اشترینان')
INSERT INTO dbo.Locations VALUES (26, 386, N' بروجرد')
INSERT INTO dbo.Locations VALUES (26, 387, N' پلدختر')
INSERT INTO dbo.Locations VALUES (26, 387, N' معمولان')
INSERT INTO dbo.Locations VALUES (26, 388, N' بیران شهر')
INSERT INTO dbo.Locations VALUES (26, 388, N' خرم آباد')
INSERT INTO dbo.Locations VALUES (26, 388, N' زاغه')
INSERT INTO dbo.Locations VALUES (26, 388, N' سپیددشت')
INSERT INTO dbo.Locations VALUES (26, 389, N' نورآباد')
INSERT INTO dbo.Locations VALUES (26, 389, N' هفت چشمه')
INSERT INTO dbo.Locations VALUES (26, 390, N' چالانچولان')
INSERT INTO dbo.Locations VALUES (26, 390, N' دورود')
INSERT INTO dbo.Locations VALUES (26, 391, N' سراب دوره')
INSERT INTO dbo.Locations VALUES (26, 391, N' ویسیان')
INSERT INTO dbo.Locations VALUES (26, 392, N' چقابل')
INSERT INTO dbo.Locations VALUES (26, 393, N' الشتر')
INSERT INTO dbo.Locations VALUES (26, 393, N' فیروزآباد')
INSERT INTO dbo.Locations VALUES (26, 394, N' درب گنبد')
INSERT INTO dbo.Locations VALUES (26, 394, N' کوهدشت')
INSERT INTO dbo.Locations VALUES (26, 394, N' کوهنانی')
INSERT INTO dbo.Locations VALUES (26, 394, N' گراب')
INSERT INTO dbo.Locations VALUES (27, 395, N' آمل')
INSERT INTO dbo.Locations VALUES (27, 395, N' امامزاده عبدالله')
INSERT INTO dbo.Locations VALUES (27, 395, N' دابودشت')
INSERT INTO dbo.Locations VALUES (27, 395, N' رینه')
INSERT INTO dbo.Locations VALUES (27, 395, N' گزنک')
INSERT INTO dbo.Locations VALUES (27, 396, N' امیرکلا')
INSERT INTO dbo.Locations VALUES (27, 396, N' بابل')
INSERT INTO dbo.Locations VALUES (27, 396, N' خوش رودپی')
INSERT INTO dbo.Locations VALUES (27, 396, N' زرگرمحله')
INSERT INTO dbo.Locations VALUES (27, 396, N' گتاب')
INSERT INTO dbo.Locations VALUES (27, 396, N' گلوگاه')
INSERT INTO dbo.Locations VALUES (27, 396, N' مرزیکلا')
INSERT INTO dbo.Locations VALUES (27, 397, N' بابلسر')
INSERT INTO dbo.Locations VALUES (27, 397, N' بهنمیر')
INSERT INTO dbo.Locations VALUES (27, 397, N' هادی شهر')
INSERT INTO dbo.Locations VALUES (27, 398, N' بهشهر')
INSERT INTO dbo.Locations VALUES (27, 398, N' خلیل شهر')
INSERT INTO dbo.Locations VALUES (27, 398, N' رستمکلا')
INSERT INTO dbo.Locations VALUES (27, 399, N' تنکابن')
INSERT INTO dbo.Locations VALUES (27, 399, N' خرم آباد')
INSERT INTO dbo.Locations VALUES (27, 399, N' شیرود')
INSERT INTO dbo.Locations VALUES (27, 399, N' نشتارود')
INSERT INTO dbo.Locations VALUES (27, 400, N' جویبار')
INSERT INTO dbo.Locations VALUES (27, 400, N' کوهی خیل')
INSERT INTO dbo.Locations VALUES (27, 401, N' چالوس')
INSERT INTO dbo.Locations VALUES (27, 401, N' مرزن آباد')
INSERT INTO dbo.Locations VALUES (27, 401, N' هچیرود')
INSERT INTO dbo.Locations VALUES (27, 402, N' رامسر')
INSERT INTO dbo.Locations VALUES (27, 402, N' کتالم وسادات شهر')
INSERT INTO dbo.Locations VALUES (27, 403, N' پایین هولار')
INSERT INTO dbo.Locations VALUES (27, 403, N' ساری')
INSERT INTO dbo.Locations VALUES (27, 403, N' فریم')
INSERT INTO dbo.Locations VALUES (27, 403, N' کیاسر')
INSERT INTO dbo.Locations VALUES (27, 404, N' آلاشت')
INSERT INTO dbo.Locations VALUES (27, 404, N' پل سفید')
INSERT INTO dbo.Locations VALUES (27, 404, N' زیرآب')
INSERT INTO dbo.Locations VALUES (27, 405, N' شیرگاه')
INSERT INTO dbo.Locations VALUES (27, 406, N' کیاکلا')
INSERT INTO dbo.Locations VALUES (27, 407, N' سلمان شهر')
INSERT INTO dbo.Locations VALUES (27, 407, N' عباس اباد')
INSERT INTO dbo.Locations VALUES (27, 407, N' کلارآباد')
INSERT INTO dbo.Locations VALUES (27, 408, N' فریدونکنار')
INSERT INTO dbo.Locations VALUES (27, 409, N' ارطه')
INSERT INTO dbo.Locations VALUES (27, 409, N' قایم شهر')
INSERT INTO dbo.Locations VALUES (27, 410, N' کلاردشت')
INSERT INTO dbo.Locations VALUES (27, 411, N' گلوگاه')
INSERT INTO dbo.Locations VALUES (27, 412, N' سرخرود')
INSERT INTO dbo.Locations VALUES (27, 412, N' محمودآباد')
INSERT INTO dbo.Locations VALUES (27, 413, N' سورک')
INSERT INTO dbo.Locations VALUES (27, 414, N' نکا')
INSERT INTO dbo.Locations VALUES (27, 415, N' ایزدشهر')
INSERT INTO dbo.Locations VALUES (27, 415, N' بلده')
INSERT INTO dbo.Locations VALUES (27, 415, N' چمستان')
INSERT INTO dbo.Locations VALUES (27, 415, N' رویان')
INSERT INTO dbo.Locations VALUES (27, 415, N' نور')
INSERT INTO dbo.Locations VALUES (27, 416, N' پول')
INSERT INTO dbo.Locations VALUES (27, 416, N' کجور')
INSERT INTO dbo.Locations VALUES (27, 416, N' نوشهر')
INSERT INTO dbo.Locations VALUES (28, 417, N' آشتیان')
INSERT INTO dbo.Locations VALUES (28, 418, N' اراک')
INSERT INTO dbo.Locations VALUES (28, 418, N' داودآباد')
INSERT INTO dbo.Locations VALUES (28, 418, N' ساروق')
INSERT INTO dbo.Locations VALUES (28, 418, N' کارچان')
INSERT INTO dbo.Locations VALUES (28, 419, N' تفرش')
INSERT INTO dbo.Locations VALUES (28, 420, N' خمین')
INSERT INTO dbo.Locations VALUES (28, 420, N' قورچی باشی')
INSERT INTO dbo.Locations VALUES (28, 421, N' جاورسیان')
INSERT INTO dbo.Locations VALUES (28, 421, N' خنداب')
INSERT INTO dbo.Locations VALUES (28, 422, N' دلیجان')
INSERT INTO dbo.Locations VALUES (28, 422, N' نراق')
INSERT INTO dbo.Locations VALUES (28, 423, N' پرندک')
INSERT INTO dbo.Locations VALUES (28, 423, N' خشکرود')
INSERT INTO dbo.Locations VALUES (28, 423, N' رازقان')
INSERT INTO dbo.Locations VALUES (28, 423, N' زاویه')
INSERT INTO dbo.Locations VALUES (28, 423, N' مامونیه')
INSERT INTO dbo.Locations VALUES (28, 424, N' آوه')
INSERT INTO dbo.Locations VALUES (28, 424, N' ساوه')
INSERT INTO dbo.Locations VALUES (28, 424, N' غرق آباد')
INSERT INTO dbo.Locations VALUES (28, 424, N' نوبران')
INSERT INTO dbo.Locations VALUES (28, 425, N' آستانه')
INSERT INTO dbo.Locations VALUES (28, 425, N' توره')
INSERT INTO dbo.Locations VALUES (28, 425, N' شازند')
INSERT INTO dbo.Locations VALUES (28, 425, N' شهباز')
INSERT INTO dbo.Locations VALUES (28, 425, N' مهاجران')
INSERT INTO dbo.Locations VALUES (28, 425, N' هندودر')
INSERT INTO dbo.Locations VALUES (28, 426, N' خنجین')
INSERT INTO dbo.Locations VALUES (28, 426, N' فرمهین')
INSERT INTO dbo.Locations VALUES (28, 427, N' کمیجان')
INSERT INTO dbo.Locations VALUES (28, 427, N' میلاجرد')
INSERT INTO dbo.Locations VALUES (28, 428, N' محلات')
INSERT INTO dbo.Locations VALUES (28, 428, N' نیمور')
INSERT INTO dbo.Locations VALUES (29, 429, N' ابوموسی')
INSERT INTO dbo.Locations VALUES (29, 430, N' بستک')
INSERT INTO dbo.Locations VALUES (29, 430, N' جناح')
INSERT INTO dbo.Locations VALUES (29, 431, N' سردشت')
INSERT INTO dbo.Locations VALUES (29, 431, N' گوهران')
INSERT INTO dbo.Locations VALUES (29, 432, N' بندرعباس')
INSERT INTO dbo.Locations VALUES (29, 432, N' تازیان پایین')
INSERT INTO dbo.Locations VALUES (29, 432, N' تخت')
INSERT INTO dbo.Locations VALUES (29, 432, N' فین')
INSERT INTO dbo.Locations VALUES (29, 432, N' قلعه قاضی')
INSERT INTO dbo.Locations VALUES (29, 433, N' بندرلنگه')
INSERT INTO dbo.Locations VALUES (29, 433, N' چارک')
INSERT INTO dbo.Locations VALUES (29, 433, N' کنگ')
INSERT INTO dbo.Locations VALUES (29, 433, N' کیش')
INSERT INTO dbo.Locations VALUES (29, 433, N' لمزان')
INSERT INTO dbo.Locations VALUES (29, 434, N' پارسیان')
INSERT INTO dbo.Locations VALUES (29, 434, N' دشتی')
INSERT INTO dbo.Locations VALUES (29, 434, N' کوشکنار')
INSERT INTO dbo.Locations VALUES (29, 435, N' بندرجاسک')
INSERT INTO dbo.Locations VALUES (29, 436, N' حاجی اباد')
INSERT INTO dbo.Locations VALUES (29, 436, N' سرگز')
INSERT INTO dbo.Locations VALUES (29, 436, N' فارغان')
INSERT INTO dbo.Locations VALUES (29, 437, N' خمیر')
INSERT INTO dbo.Locations VALUES (29, 437, N' رویدر')
INSERT INTO dbo.Locations VALUES (29, 438, N' بیکاء')
INSERT INTO dbo.Locations VALUES (29, 438, N' دهبارز')
INSERT INTO dbo.Locations VALUES (29, 438, N' زیارتعلی')
INSERT INTO dbo.Locations VALUES (29, 439, N' سیریک')
INSERT INTO dbo.Locations VALUES (29, 439, N' کوهستک')
INSERT INTO dbo.Locations VALUES (29, 439, N' گروک')
INSERT INTO dbo.Locations VALUES (29, 440, N' درگهان')
INSERT INTO dbo.Locations VALUES (29, 440, N' سوزا')
INSERT INTO dbo.Locations VALUES (29, 440, N' قشم')
INSERT INTO dbo.Locations VALUES (29, 440, N' هرمز')
INSERT INTO dbo.Locations VALUES (29, 441, N' تیرور')
INSERT INTO dbo.Locations VALUES (29, 441, N' سندرک')
INSERT INTO dbo.Locations VALUES (29, 441, N' میناب')
INSERT INTO dbo.Locations VALUES (29, 441, N' هشتبندی')
INSERT INTO dbo.Locations VALUES (30, 442, N' آجین')
INSERT INTO dbo.Locations VALUES (30, 442, N' اسدآباد')
INSERT INTO dbo.Locations VALUES (30, 443, N' بهار')
INSERT INTO dbo.Locations VALUES (30, 443, N' صالح آباد')
INSERT INTO dbo.Locations VALUES (30, 443, N' لالجین')
INSERT INTO dbo.Locations VALUES (30, 443, N' مهاجران')
INSERT INTO dbo.Locations VALUES (30, 444, N' تویسرکان')
INSERT INTO dbo.Locations VALUES (30, 444, N' سرکان')
INSERT INTO dbo.Locations VALUES (30, 444, N' فرسفج')
INSERT INTO dbo.Locations VALUES (30, 445, N' دمق')
INSERT INTO dbo.Locations VALUES (30, 445, N' رزن')
INSERT INTO dbo.Locations VALUES (30, 445, N' قروه درجزین')
INSERT INTO dbo.Locations VALUES (30, 446, N' فامنین')
INSERT INTO dbo.Locations VALUES (30, 447, N' شیرین سو')
INSERT INTO dbo.Locations VALUES (30, 447, N' کبودرآهنگ')
INSERT INTO dbo.Locations VALUES (30, 447, N' گل تپه')
INSERT INTO dbo.Locations VALUES (30, 448, N' ازندریان')
INSERT INTO dbo.Locations VALUES (30, 448, N' جوکار')
INSERT INTO dbo.Locations VALUES (30, 448, N' زنگنه')
INSERT INTO dbo.Locations VALUES (30, 448, N' سامن')
INSERT INTO dbo.Locations VALUES (30, 448, N' ملایر')
INSERT INTO dbo.Locations VALUES (30, 449, N' برزول')
INSERT INTO dbo.Locations VALUES (30, 449, N' فیروزان')
INSERT INTO dbo.Locations VALUES (30, 449, N' گیان')
INSERT INTO dbo.Locations VALUES (30, 449, N' نهاوند')
INSERT INTO dbo.Locations VALUES (30, 450, N' جورقان')
INSERT INTO dbo.Locations VALUES (30, 450, N' قهاوند')
INSERT INTO dbo.Locations VALUES (30, 450, N' مریانج')
INSERT INTO dbo.Locations VALUES (30, 450, N' همدان')
INSERT INTO dbo.Locations VALUES (31, 451, N' ابرکوه')
INSERT INTO dbo.Locations VALUES (31, 451, N' مهردشت')
INSERT INTO dbo.Locations VALUES (31, 452, N' احمدآباد')
INSERT INTO dbo.Locations VALUES (31, 452, N' اردکان')
INSERT INTO dbo.Locations VALUES (31, 452, N' عقدا')
INSERT INTO dbo.Locations VALUES (31, 453, N' اشکذر')
INSERT INTO dbo.Locations VALUES (31, 453, N' خضرآباد')
INSERT INTO dbo.Locations VALUES (31, 454, N' بافق')
INSERT INTO dbo.Locations VALUES (31, 455, N' بهاباد')
INSERT INTO dbo.Locations VALUES (31, 456, N' تفت')
INSERT INTO dbo.Locations VALUES (31, 456, N' نیر')
INSERT INTO dbo.Locations VALUES (31, 457, N' مروست')
INSERT INTO dbo.Locations VALUES (31, 457, N' هرات')
INSERT INTO dbo.Locations VALUES (31, 458, N' مهریز')
INSERT INTO dbo.Locations VALUES (31, 459, N' بفروییه')
INSERT INTO dbo.Locations VALUES (31, 459, N' میبد')
INSERT INTO dbo.Locations VALUES (31, 459, N' ندوشن')
INSERT INTO dbo.Locations VALUES (31, 460, N' حمیدیا')
INSERT INTO dbo.Locations VALUES (31, 460, N' زارچ')
INSERT INTO dbo.Locations VALUES (31, 460, N' شاهدیه')
INSERT INTO dbo.Locations VALUES (31, 460, N' یزد')
